---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, SAP HANA database, virtual machine, vm 
summary: Esta versión de NetApp Backup and Recovery tiene las siguientes limitaciones conocidas. 
---
= Limitaciones conocidas de NetApp Backup and Recovery para cargas de trabajo KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Consulta las limitaciones actuales para las cargas de trabajo KVM en NetApp Backup and Recovery.

Las siguientes acciones y configuraciones no compatibles se aplican a las cargas de trabajo KVM en NetApp Backup and Recovery:



[[unsupported-actions]]
== Acciones no admitidas

Las siguientes acciones no son compatibles:

* En la versión preliminar de Backup and Recovery para la implementación local de NetApp Console, las copias de seguridad en almacenamiento de objetos solo son compatibles con destinos ONTAP S3 y StorageGRID. El archivado de copias de seguridad no es compatible en esta versión preliminar.
* Clonar, montar o desmontar máquinas virtuales
* Proteger las máquinas virtuales almacenadas en SAN
* Proteger aplicaciones
* Crear copias de seguridad definidas por el usuario (solo se admiten las copias de seguridad iniciadas desde la NetApp Console )




[[unsupported-configurations]]
== Configuraciones no compatibles

Las siguientes configuraciones no son compatibles:

* Control de acceso basado en roles (RBAC)
* Discos conectados directamente al host KVM
* Discos distribuidos en múltiples puntos de montaje o recursos compartidos de NFS
* Formato de disco RAW
* Tipos de grupos de almacenamiento distintos de NetFS (solo se admite NetFS)




[[troubleshooting-notes]]
== Notas de solución de problemas

Ten en cuenta lo siguiente cuando utilices cargas de trabajo KVM con NetApp Backup and Recovery.

* Las copias de seguridad pueden fallar si el agente de invitado de QEMU no se está ejecutando en una máquina virtual protegida. Para evitar este problema, asegúrate de que el demonio `qemu-guest-agent` esté ejecutándose en la máquina virtual antes de iniciar la copia de seguridad.

