---
sidebar: sidebar 
permalink: br-limitations-kubernetes.html 
keywords: limitations, known, NetApp Backup and Recovery, Kubernetes, applications, workloads 
summary: Revisa estas limitaciones de NetApp Backup and Recovery antes de usar Backup and Recovery en tu entorno. 
---
= Limitaciones conocidas con NetApp Backup and Recovery para cargas de trabajo de Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Aquí se enumeran las plataformas, dispositivos o funciones que no funcionan o no funcionan bien con esta versión.  Lea estas limitaciones cuidadosamente.



[[backup-and-recovery-preview-for-netapp-console-local-deployment-limitation]]
=== Limitación de la versión preliminar de Backup and Recovery para la implementación local de NetApp Console

En la versión preliminar de Backup and Recovery para la implementación local de NetApp Console, las copias de seguridad en almacenamiento de objetos solo son compatibles con destinos ONTAP S3 y StorageGRID. El archivado de copias de seguridad no es compatible en esta versión preliminar.



[[changing-the-protection-policy-for-an-application]]
== Cambiar la política de protección de una aplicación

Cuando cambias la política de protección asociada a una aplicación para usar un bucket u objetivo de replicación secundario diferente, la política de protección puede fallar.

*Solución*: elimina y vuelve a añadir la aplicación.



[[3-2-1-protection-policy-configuration-limitation]]
== Limitación de la configuración de la política de protección 3-2-1

Cuando creas una política de protección 3-2-1 donde no se realizan copias de seguridad en el almacén de objetos al mismo tiempo que la replicación al almacenamiento secundario, la política de protección se queda colgada al proteger la aplicación.

*Solución*: elimina y vuelve a agregar la aplicación y protégela con una política de protección diferente.
