---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: Esta versión de NetApp Backup and Recovery tiene las siguientes limitaciones conocidas. 
---
= Limitaciones conocidas de NetApp Backup and Recovery para cargas de trabajo KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Aquí se enumeran las plataformas, dispositivos o funciones que no funcionan o no funcionan bien con esta versión.  Lea estas limitaciones cuidadosamente.

Las siguientes acciones y configuraciones no son compatibles con la versión preliminar privada de las cargas de trabajo KVM en NetApp Backup and Recovery:



== Acciones no admitidas

Las siguientes acciones no son compatibles con la versión preliminar privada:

* Clonar, montar o desmontar máquinas virtuales
* Restaurar máquinas virtuales a una ubicación alternativa
* Proteger las máquinas virtuales almacenadas en SAN
* Proteger aplicaciones
* Editar grupos de protección
* Crear grupos de protección utilizando máquinas virtuales de varios hosts KVM
* Crear copias de seguridad definidas por el usuario (solo se admiten las copias de seguridad iniciadas desde la NetApp Console )




== Configuraciones no compatibles

Las siguientes configuraciones no son compatibles:

* Control de acceso basado en roles (RBAC)
* Discos conectados directamente al host KVM
* Discos distribuidos en múltiples puntos de montaje o recursos compartidos de NFS
* Formato de disco RAW
* Tipos de grupos de almacenamiento distintos de NetFS (solo se admite NetFS)




== Cuentas de NetApp Console heredadas no compatibles

Las cuentas de NetApp Console heredadas no admiten las funciones necesarias para proteger las cargas de trabajo de KVM.  Comprueba si estás usando una cuenta heredada en la interfaz de usuario web de la consola.  Si tiene una cuenta de consola heredada, cree una cuenta nueva antes de proteger las cargas de trabajo de KVM.

.Pasos
. Desde el menú de la NetApp Console , seleccione *Administración > Identidad y acceso*.
. En *Organización*, verifique si se muestra un *ID de cuenta* junto al ID de la organización.
+
Si se muestra un *ID de cuenta*, estás utilizando una cuenta heredada.

. Si está utilizando una cuenta heredada, haga lo siguiente:
+
.. Cierre la sesión de la consola y luego navegue hasta la https://console.netapp.com/["Página de inicio de sesión de la consola"^] .
.. Seleccione *Registrarse* para crear una nueva cuenta.



