---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: Esta versión de NetApp Backup and Recovery tiene las siguientes limitaciones conocidas. 
---
= Limitaciones conocidas de NetApp Backup and Recovery para cargas de trabajo KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Aquí se enumeran las plataformas, dispositivos o funciones que no funcionan o no funcionan bien con esta versión.  Lea estas limitaciones cuidadosamente.

Las siguientes acciones y configuraciones no son compatibles con la versión preliminar privada de las cargas de trabajo KVM en NetApp Backup and Recovery:



== Acciones no admitidas

Las siguientes acciones no son compatibles con la versión preliminar privada:

* Clonar, montar o desmontar máquinas virtuales
* Restaurar máquinas virtuales a una ubicación alternativa
* Proteger las máquinas virtuales almacenadas en SAN
* Proteger aplicaciones
* Editar grupos de protección
* Crear grupos de protección utilizando máquinas virtuales de varios hosts KVM
* Crear copias de seguridad definidas por el usuario (solo se admiten las copias de seguridad iniciadas desde la NetApp Console )




== Configuraciones no compatibles

Las siguientes configuraciones no son compatibles:

* Control de acceso basado en roles (RBAC)
* Discos conectados directamente al host KVM
* Discos distribuidos en múltiples puntos de montaje o recursos compartidos de NFS
* Formato de disco RAW
* Tipos de grupos de almacenamiento distintos de NetFS (solo se admite NetFS)




== Notas de solución de problemas

Tenga en cuenta lo siguiente al utilizar la vista previa privada de cargas de trabajo KVM con NetApp Backup and Recovery:

* Para garantizar que las restauraciones de la carga de trabajo de KVM se completen correctamente, asegúrese de que la configuración *Habilitar instantánea consistente con VM* esté activa en la política de protección que utiliza para las copias de seguridad de KVM.
* No puede realizar una copia de seguridad de un grupo de almacenamiento con hosts KVM administrados por Apache CloudStack a menos que agregue todos los hosts administrados a NetApp Backup and Recovery. Como solución alternativa, agregue todos los host KVM administrados por CloudStack a NetApp Backup and Recovery.
* No se puede realizar una copia de seguridad de una máquina virtual detenida que pertenece a un grupo de protección. Como solución alternativa, elimine la máquina virtual detenida del grupo de protección antes de iniciar la copia de seguridad.

