---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, SAP HANA database, virtual machine, vm 
summary: Esta versión de NetApp Backup and Recovery tiene las siguientes limitaciones conocidas. 
---
= Limitaciones conocidas de NetApp Backup and Recovery para cargas de trabajo KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Aquí se enumeran las plataformas, dispositivos o funciones que no funcionan o no funcionan bien con esta versión.  Lea estas limitaciones cuidadosamente.

Las siguientes acciones y configuraciones no son compatibles en cargas de trabajo KVM en NetApp Backup and Recovery:



[[unsupported-actions]]
== Acciones no admitidas

Las siguientes acciones no son compatibles:

* En la versión preliminar de Backup and Recovery para la implementación local de NetApp Console, las copias de seguridad en almacenamiento de objetos solo son compatibles con destinos ONTAP S3 y StorageGRID. El archivado de copias de seguridad no es compatible en esta versión preliminar.
* Clonar, montar o desmontar máquinas virtuales
* Proteger las máquinas virtuales almacenadas en SAN
* Proteger aplicaciones
* Crear copias de seguridad definidas por el usuario (solo se admiten las copias de seguridad iniciadas desde la NetApp Console )




[[unsupported-configurations]]
== Configuraciones no compatibles

Las siguientes configuraciones no son compatibles:

* Control de acceso basado en roles (RBAC)
* Discos conectados directamente al host KVM
* Discos distribuidos en múltiples puntos de montaje o recursos compartidos de NFS
* Formato de disco RAW
* Tipos de grupos de almacenamiento distintos de NetFS (solo se admite NetFS)




[[troubleshooting-notes]]
== Notas de solución de problemas

Ten en cuenta lo siguiente cuando uses cargas de trabajo KVM con NetApp Backup and Recovery.

* Las copias de seguridad pueden fallar si el agente invitado QEMU no se está ejecutando en una máquina virtual protegida. Como solución, asegúrate de que el daemon `qemu-guest-agent` se está ejecutando en la máquina virtual antes de iniciar la copia de seguridad.

