---
sidebar: sidebar 
permalink: br-limitations-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Hyper-V, SAP HANA database, virtual machine, vm 
summary: NetApp Backup and Recovery primero debe descubrir los datos para que usted pueda utilizar el servicio.  Durante el descubrimiento, NetApp Backup and Recovery analiza todos los volúmenes y archivos de los sistemas de su organización. 
---
= Limitaciones conocidas de NetApp Backup and Recovery para cargas de trabajo de Hyper-V
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Aquí se enumeran las plataformas, dispositivos o funciones que no funcionan o no funcionan bien con esta versión.  Lea estas limitaciones cuidadosamente.



== Acciones no admitidas

Las siguientes acciones no son compatibles con la versión preliminar privada de las cargas de trabajo de Hyper-V en NetApp Backup and Recovery:

* Crear grupos de recursos
* Expansión de discos (en varios recursos compartidos CIFS)
* Proteger las máquinas virtuales a través de SAN
* Editar grupos de protección
* Proteja los hosts de Hyper-V que están agrupados mediante System Center Virtual Machine Manager (SCVMM)




== Cuentas de NetApp Console heredadas no compatibles

Las cuentas de NetApp Console heredadas no admiten las funciones necesarias para proteger las cargas de trabajo de Hyper-V.  Comprueba si estás usando una cuenta heredada en la interfaz de usuario web de la consola.  Si tiene una cuenta de consola heredada, cree una cuenta nueva antes de proteger las cargas de trabajo de Hyper-V.

.Pasos
. Desde el menú de la NetApp Console , seleccione *Administración > Identidad y acceso*.
. En *Organización*, verifique si se muestra un *ID de cuenta* junto al ID de la organización.
+
Si se muestra un *ID de cuenta*, estás utilizando una cuenta heredada.

. Si está utilizando una cuenta heredada, haga lo siguiente:
+
.. Cierre la sesión de la consola y luego navegue hasta la https://console.netapp.com/["Página de inicio de sesión de la consola"^] .
.. Seleccione *Registrarse* para crear una nueva cuenta.



