---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: backup, back up, restore, recovery, aws, azure 
summary: Antes de utilizar NetApp Backup and Recovery, realice algunos pasos para configurar los destinos de respaldo. 
---
= Configure destinos de respaldo antes de usar NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Antes de utilizar NetApp Backup and Recovery, realice algunos pasos para configurar los destinos de respaldo.

Antes de comenzar, reviselink:concept-start-prereq.html["prerrequisitos"] para garantizar que su entorno esté preparado.



== Preparar el destino de la copia de seguridad

Prepare uno o más de los siguientes destinos de respaldo:

* StorageGRID NetApp .
+
Referirse a https://docs.netapp.com/us-en/storage-management-storagegrid/task-discover-storagegrid.html["Descubra StorageGRID"^] .

+
Referirse a https://docs.netapp.com/us-en/storagegrid/index.html["Documentación de StorageGRID"^] para obtener detalles sobre StorageGRID.

* Servicios web de Amazon.  Referirse a https://docs.netapp.com/us-en/storage-management-s3-storage/index.html["Documentación de Amazon S3"^] .
+
Haga lo siguiente para preparar AWS como destino de respaldo:

+
** Configurar una cuenta en AWS.
** Configure los permisos S3 en AWS, que se enumeran en la siguiente sección.
** Para obtener detalles sobre cómo administrar su almacenamiento de AWS en la consola, consulte https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["Administra tus buckets de Amazon S3"^] .


* Microsoft Azure.
+
** Referirse a https://docs.netapp.com/us-en/storage-management-azure-netapp-files/index.html["Documentación de Azure NetApp Files"^] .
** Configurar una cuenta en Azure.
** Configurar https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Permisos de Azure"^] en Azure.
** Para obtener detalles sobre cómo administrar su almacenamiento de Azure en la consola, consulte https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["Administrar sus cuentas de almacenamiento de Azure"^] .




Después de configurar las opciones en el destino de la copia de seguridad, más tarde lo configurará como destino de copia de seguridad en NetApp Backup and Recovery.  Para obtener detalles sobre cómo configurar el destino de la copia de seguridad en NetApp Backup and Recovery, consultelink:br-start-discover-backup-targets.html["Descubrir objetivos de respaldo"] .



== Configurar permisos S3

Necesitará configurar dos conjuntos de permisos de AWS S3:

* Permisos para que el agente de la consola cree y administre el depósito S3.
* Permisos para el clúster ONTAP local para que pueda leer y escribir datos en el depósito S3.


.Pasos
. Asegúrese de que el agente de la consola tenga los permisos necesarios.  Para más detalles, consulte https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-aws.html["Permisos de políticas de la NetApp Console"] .
+

NOTE: Al crear copias de seguridad en las regiones de AWS China, debe cambiar el nombre del recurso de AWS "arn" en todas las secciones _Resource_ en las políticas de IAM de "aws" a "aws-cn"; por ejemplo `arn:aws-cn:s3:::netapp-backup-*` .

. Cuando active el servicio, el asistente de copia de seguridad le solicitará que ingrese una clave de acceso y una clave secreta.  Estas credenciales se pasan al clúster de ONTAP para que ONTAP pueda realizar copias de seguridad y restaurar datos en el depósito S3.  Para ello, necesitarás crear un usuario IAM con los siguientes permisos.
+
Consulte la https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["Documentación de AWS: Creación de un rol para delegar permisos a un usuario de IAM"^] .

+
[%collapsible]
====
[source, json]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:ListBucket",
        "s3:ListAllMyBuckets",
        "s3:GetBucketLocation",
        "s3:PutEncryptionConfiguration"
      ],
      "Resource": "arn:aws:s3:::netapp-backup-*",
      "Effect": "Allow",
      "Sid": "backupPolicy"
    },
    {
      "Action": [
        "s3:ListBucket",
        "s3:GetBucketLocation"
      ],
      "Resource": "arn:aws:s3:::netapp-backup*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:ListAllMyBuckets",
        "s3:PutObjectTagging",
        "s3:GetObjectTagging",
        "s3:RestoreObject",
        "s3:GetBucketObjectLockConfiguration",
        "s3:GetObjectRetention",
        "s3:PutBucketObjectLockConfiguration",
        "s3:PutObjectRetention"
      ],
      "Resource": "arn:aws:s3:::netapp-backup*/*",
      "Effect": "Allow"
    }
  ]
}
----
====

