---
sidebar: sidebar 
permalink: br-start-discover-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, workloads, protect 
summary: NetApp Backup and Recovery primero debe descubrir las cargas de trabajo para poder protegerlas. 
---
= Descubra las cargas de trabajo KVM en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery necesita descubrir hosts KVM y máquinas virtuales antes de protegerlos.

*Rol de consola requerido* Superadministrador de Copia de seguridad y recuperación.  Conozca más sobrelink:reference-roles.html["Roles y privilegios de copia de seguridad y recuperación"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^] .



== Agregue un host KVM y descubra recursos

Agregue información del host KVM y permita que NetApp Backup and Recovery descubra cargas de trabajo. Dentro de cada agente de consola, seleccione los sistemas en los que desea descubrir cargas de trabajo.

.Pasos
. Desde el menú de la NetApp Console , seleccione *Protección > Copia de seguridad y recuperación*.
. En el mosaico KVM, seleccione *Descubrir y administrar*.
+
Si es la primera vez que inicia sesión en Backup and Recovery, ya tiene un sistema en la consola, pero no ha descubierto ningún recurso, aparece la página de inicio "Bienvenido al nuevo NetApp Backup and Recovery" y muestra una opción para *Descubrir recursos*.

. Seleccione *Descubrir recursos*.
. Introduzca la siguiente información:
+
.. *Tipo de carga de trabajo*: Seleccione *KVM*.
.. Si aún no ha almacenado las credenciales para este host KVM, seleccione *Agregar credenciales*.
+
... Seleccione el agente de consola que se utilizará con este host.
... Introduzca un nombre para esta credencial.
... Elija si desea utilizar credenciales root o credenciales no root.
... Introduzca el nombre de usuario y la contraseña de la cuenta.
... Seleccione *Listo*.


.. *Registro de host*: agregue un nuevo host KVM.  Ingrese el FQDN o la dirección IP del host, las credenciales, el agente de consola y el número de puerto.


. Seleccione *Descubrir*.
+

TIP: Este proceso puede tardar unos minutos.



.Resultado
La carga de trabajo de KVM se muestra en la lista de cargas de trabajo en la página Inventario.



== Continuar al panel de control de NetApp Backup and Recovery

.Pasos
. Desde el menú de la NetApp Console , seleccione *Protección* > *Copia de seguridad y recuperación*.
. Seleccione un mosaico de carga de trabajo (por ejemplo, Microsoft SQL Server).
. Desde el menú Copia de seguridad y recuperación, seleccione *Panel de control*.
. Revisar la salud de la protección de datos.  La cantidad de cargas de trabajo en riesgo o protegidas aumenta según las cargas de trabajo recientemente descubiertas, protegidas y respaldadas.

