---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: NetApp Backup and Recovery primero debe descubrir las cargas de trabajo para que usted pueda utilizar el servicio. 
---
= Descubra las cargas de trabajo de Kubernetes en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubre los clústeres de Kubernetes y sus cargas de trabajo en NetApp Backup and Recovery para que puedas protegerlos con políticas de protección.

*Rol requerido de NetApp Console*: superadministrador de Backup and Recovery. Si estás protegiendo datos almacenados en un clúster de Cloud Volumes ONTAP, también se requiere el rol de Cloud Volumes ONTAP Admin. Conoce más sobre link:reference-roles.html["Roles y privilegios de copia de seguridad y recuperación"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].



[[discover-kubernetes-workloads]]
== Descubra las cargas de trabajo de Kubernetes

En el inventario de Backup and Recovery, detecta los clústeres y las cargas de trabajo de Kubernetes de tu entorno. Al añadir un clúster, puedes registrarlo en NetApp Backup and Recovery y descubrir sus aplicaciones y recursos para protegerlos. Opcionalmente, puedes descubrir recursos locales de Kubernetes aislados físicamente usando la implementación local de NetApp Console.

[NOTE]
====
Cuando detectes un clúster protegido actualmente con Trident Protect, las programaciones de copia de seguridad utilizadas con Trident Protect se desactivan durante el proceso de detección, ya que las programaciones de copia de seguridad de Trident Protect no son compatibles con Backup and Recovery. Para proteger las aplicaciones del clúster, link:br-use-policies-create.html["crear una nueva política de protección"] o asocia las aplicaciones con una política existente. Luego puedes eliminar las programaciones de copia de seguridad de Trident Protect si lo necesitas.

====
.Pasos
. Debe realizar una de las siguientes acciones:
+
** Si está descubriendo cargas de trabajo de Kubernetes por primera vez, en NetApp Backup and Recovery, en *Cargas de trabajo*, seleccione el mosaico *Kubernetes*.
** Si ya ha descubierto cargas de trabajo de Kubernetes, en NetApp Backup and Recovery, seleccione *Inventario* > *Cargas de trabajo* y luego seleccione *Descubrir recursos*.


. Seleccione el tipo de carga de trabajo *Kubernetes*.
. Introduce un nombre para el clúster y selecciona un agente de Console para usarlo con el clúster.
+
Backup and Recovery ofrece instrucciones que varían según el tipo de instalación que elijas. Si usas una implementación local de NetApp Console, puedes elegir instrucciones para descubrir recursos aislados que no tienen conectividad a redes externas.

. Elige un tipo de instalación para ver las instrucciones para instalar Trident Protect en tu clúster de Kubernetes:
+
** Selecciona *Conectado* para detectar los clústeres que tienen conectividad de red externa.
** Selecciona «*Air-gapped*» para detectar clústeres que no tienen conectividad con redes externas.
+
[role="tabbed-block"]
====
.Descubrimiento conectado
--
... Sigue las instrucciones de la línea de comandos que aparecen en Backup and Recovery. Estos pasos garantizan que Backup and Recovery pueda interactuar con el clúster.


--
.Detección air-gapped
--
... Introduce la URL de tu registro privado de contenedores Docker. Este registro se utiliza para descargar las imágenes de Trident Protect y Trident Protect Connector durante la instalación.
... Si tu registro privado de contenedores requiere autenticación, utiliza uno de los siguientes métodos para configurar las credenciales del registro:
+
**** *Autenticación a nivel de nodo*: Configura las credenciales del registro en el entorno de ejecución del contenedor en cada nodo. Una vez configurado, todos los pods pueden descargar imágenes sin necesidad de ajustes adicionales en Helm.
**** *Secreto de descarga de imágenes de Kubernetes*: Crea un secreto de descarga de imágenes de Kubernetes en el espacio de nombres  `trident-protect` y luego haz referencia a él durante el paso de actualización de Helm en las instrucciones de instalación de Trident Protect:
+
[source, console]
----
--set trident-protect.imagePullSecrets[0].name=<pull-secret-name>
--set connector.imagePullSecrets[0].name=<pull-secret-name>
----


... Sigue las instrucciones de la línea de comandos que aparecen en Backup and Recovery, añadiendo la información secreta para la descarga de la imagen durante el paso de Helm (si es necesario). Estos pasos garantizan que Backup and Recovery pueda interactuar con el clúster.


--
====


. Una vez que hayas completado los pasos de instalación de Trident Protect, selecciona *Discover*.
+
El clúster se agrega al inventario.

. Seleccione *Ver* en la carga de trabajo de Kubernetes asociada para ver la lista de aplicaciones, clústeres y espacios de nombres para esa carga de trabajo.




[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Continuar al panel de control de NetApp Backup and Recovery

Sigue estos pasos para ver el panel de control de NetApp Backup and Recovery y verificar los recursos detectados.

. Desde el menú de la NetApp Console , seleccione *Protección* > *Copia de seguridad y recuperación*.
. Selecciona el mosaico de la carga de trabajo de Kubernetes.
. Desde el menú Copia de seguridad y recuperación, seleccione *Panel de control*.
. Revisar la salud de la protección de datos.  La cantidad de cargas de trabajo en riesgo o protegidas aumenta según las cargas de trabajo recientemente descubiertas, protegidas y respaldadas.
+
link:br-use-dashboard.html["Descubra lo que le muestra el Dashboard"].


