---
sidebar: sidebar 
permalink: br-start-login.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Utilice la NetApp Console para iniciar sesión en el servicio de NetApp Backup and Recovery . 
---
= Inicie sesión en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilice la NetApp Console para iniciar sesión en NetApp Backup and Recovery.

NetApp Backup and Recovery utiliza la gestión de identidad y acceso para controlar lo que puede hacer cada usuario.

Para obtener detalles sobre las acciones que puede realizar cada rol, consultelink:reference-roles.html["Roles de usuario de NetApp Backup and Recovery"] .

Para iniciar sesión en la NetApp Console, puede utilizar sus credenciales del sitio de soporte de NetApp o puede registrarse para iniciar sesión en la NetApp Console usando su correo electrónico y una contraseña. https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["Obtenga más información sobre cómo iniciar sesión"^] .

*Rol de NetApp Console requerido* Rol de superadministrador de Backup and Recovery o rol de administrador de restauración de Backup and Recovery. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^] .

Para agregar un agente de consola, debe tener el rol de superadministrador de Copia de seguridad y recuperación.

.Pasos
. Abra un navegador web y vaya a https://console.netapp.com/["NetApp Console"^] .
+
Aparece la página de inicio de sesión de la NetApp Console .

. Inicie sesión en la consola.
. Desde la navegación izquierda de la Consola, seleccione *Protección* > *Copia de seguridad y recuperación*.
+
** Si es la primera vez que inicia sesión en Backup and Recovery y aún no ha agregado un sistema a la página *Sistemas*, Backup and Recovery muestra la página de inicio "Bienvenido a la nueva NetApp Backup and Recovery" y brinda una opción para agregar un sistema.  Para obtener detalles sobre cómo agregar un sistema a la página *Sistemas*, consulte https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Introducción al modo estándar de la NetApp Console"^] .
** Si es la primera vez que inicia sesión en Backup and Recovery y ya agregó un sistema a la página *Sistemas*, pero no descubrió ningún recurso, aparece la página de inicio "Bienvenido al nuevo NetApp Backup and Recovery" y muestra una opción para *Descubrir recursos*.


. Si aún no lo ha hecho, seleccione la opción *Descubrir y administrar*.
+
** Para cargas de trabajo de Microsoft SQL Server, consultelink:br-start-discover.html["Descubra las cargas de trabajo de Microsoft SQL Server"] .
** Para cargas de trabajo de VMware, consultelink:br-use-vmware-discovery.html["Descubra las cargas de trabajo de VMware"] .
** Para cargas de trabajo KVM, consultelink:br-start-discover-kvm.html["Descubra las cargas de trabajo KVM"] .
** Para las cargas de trabajo de Oracle, consultelink:br-start-discover-oracle.html["Descubra las cargas de trabajo de Oracle"] .
** Para cargas de trabajo de Hyper-V, consultelink:br-start-discover-hyperv.html["Descubra las cargas de trabajo de Hyper-V"] .
** Para cargas de trabajo de Kubernetes, consultelink:br-start-discover-kubernetes.html["Descubra las cargas de trabajo de Kubernetes"] .



