---
sidebar: sidebar 
permalink: br-start-discover-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle 
summary: NetApp Backup and Recovery primero debe descubrir las cargas de trabajo para poder protegerlas. 
---
= Descubre las cargas de trabajo de Oracle Database en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubrir bases de datos Oracle permite que NetApp Backup and Recovery las proteja creando y restaurando backups e instantáneas.

*Rol de consola requerido* Superadministrador de Copia de seguridad y recuperación.  Conozca más sobrelink:reference-roles.html["Roles y privilegios de copia de seguridad y recuperación"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^] .



== Añade un host de base de datos Oracle y descubre recursos

Agregue información del host de Oracle y permita que NetApp Backup and Recovery descubra cargas de trabajo. Dentro de cada agente de consola, seleccione los sistemas en los que desea descubrir cargas de trabajo.

.Pasos
. Desde el menú de la NetApp Console , seleccione *Protección > Copia de seguridad y recuperación*.
. En *Cargas de trabajo*, seleccione el mosaico *Oracle*.
. Seleccione *Descubrir recursos*.
. Selecciona *Oracle* para el campo *Tipo de carga de trabajo*.
. Si aún no has almacenado credenciales para este host de Oracle Database, selecciona *Add credentials*.
+
.. Seleccione el agente de consola que se utilizará con este host.
.. Introduzca un nombre para esta credencial.
.. Introduzca el nombre de usuario y la contraseña de la cuenta.
.. Seleccione *Listo*.


. *Registro de host*: Añade un nuevo host de Oracle Database. En el campo *Host FQDN or IP address*, introduce el FQDN o la dirección IP del host; para bases de datos en clúster puedes introducir el FQDN o la IP de cualquier nodo del clúster. Luego proporciona las credenciales, el agente de la Console y el número de puerto.
. (Opcional) Si eliges credenciales para un usuario que no es root, haz lo siguiente:
+
.. Para obtener instrucciones sobre cómo agregar el usuario no root que seleccionaste al archivo sudoers en el host de Oracle Database, selecciona *Configure sudoers*.
.. Sigue las instrucciones en el cuadro de diálogo, activa la casilla cuando termines y selecciona *Done*.


. *Configuración avanzada*: haz lo siguiente:
+
.. Introduce el puerto y la ruta de instalación que quieres usar para el NetApp plug-in. El plug-in permite la comunicación entre el host de la base de datos Oracle y NetApp Backup and Recovery.
.. Elige si quieres permitir que NetApp Backup and Recovery instale el complemento automáticamente en cada host o saltar la instalación automática del complemento para todos los hosts. Selecciona *Muéstrame cómo* para ver las instrucciones de instalación manual.
+
[NOTE]
====
Backup and Recovery se conecta a cada host a través de SSH para instalar el complemento automáticamente. Activa *Usar instalación manual* cuando se dé cualquiera de los siguientes casos:

*** Uno o más hosts no están ejecutando el servicio SSH.
*** Cualquier host ya dispone del complemento NetApp (incluso si solo lo tienen algunos miembros del clúster).
*** Prefieres instalar el plug-in en cada host manualmente.


====
.. Si el host de la base de datos está en clúster, activa la opción *Add all hosts in the cluster* para descubrir todos los hosts del clúster.
.. Elige si quieres ejecutar comprobaciones de preinstalación en cada host antes de instalar automáticamente el plug-in. Si las comprobaciones fallan, se detiene la instalación automática del plug-in. Para omitir las comprobaciones e instalar de todos modos, activa *Skip optional preinstall checks* (se activa automáticamente si eliges la instalación manual).


. Seleccione *Descubrir*.
+

TIP: Añadir recursos puede llevar varios minutos. Para ver el progreso, selecciona *Seguir progreso* en el cuadro de diálogo de estado en la parte inferior de la página de Inventario o selecciona *Supervisión* en el menú de la izquierda.



.Resultado
La carga de trabajo de Oracle Database se muestra en la lista de cargas de trabajo en la página Inventory.



== Continuar al panel de control de NetApp Backup and Recovery

. Desde el menú de la NetApp Console , seleccione *Protección* > *Copia de seguridad y recuperación*.
. Seleccione un mosaico de carga de trabajo (por ejemplo, Microsoft SQL Server).
. Desde el menú Copia de seguridad y recuperación, seleccione *Panel de control*.
. Revisar la salud de la protección de datos.  La cantidad de cargas de trabajo en riesgo o protegidas aumenta según las cargas de trabajo recientemente descubiertas, protegidas y respaldadas.

