---
sidebar: sidebar 
permalink: br-start-discover-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle 
summary: NetApp Backup and Recovery primero debe descubrir las cargas de trabajo para poder protegerlas. 
---
= Descubre las cargas de trabajo de Oracle Database en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubrir bases de datos Oracle permite que NetApp Backup and Recovery las proteja creando y restaurando backups e instantáneas.

*Rol de consola requerido* Superadministrador de Copia de seguridad y recuperación.  Conozca más sobrelink:reference-roles.html["Roles y privilegios de copia de seguridad y recuperación"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^] .



== Añade un host de base de datos Oracle y descubre recursos

Agregue información del host de Oracle y permita que NetApp Backup and Recovery descubra cargas de trabajo. Dentro de cada agente de consola, seleccione los sistemas en los que desea descubrir cargas de trabajo.

.Pasos
. Desde el menú de la NetApp Console , seleccione *Protección > Copia de seguridad y recuperación*.
. En *Cargas de trabajo*, seleccione el mosaico *Oracle*.
+
Si inicia sesión en Backup and Recovery por primera vez y tiene un sistema en la consola pero no ha descubierto ningún recurso, aparecerá la página _Bienvenido a la nueva NetApp Backup and Recovery_ con una opción para *Descubrir recursos*.

. Seleccione *Descubrir recursos*.
. Selecciona *Oracle* para el campo *Tipo de carga de trabajo*.
. Si aún no has almacenado credenciales para este host de Oracle Database, selecciona *Add credentials*.
+
.. Seleccione el agente de consola que se utilizará con este host.
.. Introduzca un nombre para esta credencial.
.. Introduzca el nombre de usuario y la contraseña de la cuenta.
.. Seleccione *Listo*.


. *Registro de host*: agrega un nuevo host de Oracle Database. Introduce el FQDN o la dirección IP del host, las credenciales, el agente de la consola y el número de puerto.
. (Opcional) Si eliges credenciales para un usuario que no es root, haz lo siguiente:
+
.. Para obtener instrucciones sobre cómo agregar el usuario no root que seleccionaste al archivo sudoers en el host de Oracle Database, selecciona *Configure sudoers*.
.. Sigue las instrucciones en el cuadro de diálogo, activa la casilla cuando termines y selecciona *Done*.


. *Configuración avanzada*: haz lo siguiente:
+
.. Introduce el puerto y la ruta de instalación que quieres usar para el NetApp plug-in. El plug-in permite la comunicación entre el host de la base de datos Oracle y NetApp Backup and Recovery.
.. Elige si quieres permitir que NetApp Backup and Recovery instale el complemento automáticamente o saltar la instalación (tendrás que instalar el complemento manualmente en el host).
.. Elige si quieres realizar comprobaciones previas a la instalación o saltártelas.


. Seleccione *Descubrir*.
+

TIP: Este proceso puede tardar unos minutos.



.Resultado
La carga de trabajo de Oracle Database se muestra en la lista de cargas de trabajo en la página Inventory.



== Continuar al panel de control de NetApp Backup and Recovery

. Desde el menú de la NetApp Console , seleccione *Protección* > *Copia de seguridad y recuperación*.
. Seleccione un mosaico de carga de trabajo (por ejemplo, Microsoft SQL Server).
. Desde el menú Copia de seguridad y recuperación, seleccione *Panel de control*.
. Revisar la salud de la protección de datos.  La cantidad de cargas de trabajo en riesgo o protegidas aumenta según las cargas de trabajo recientemente descubiertas, protegidas y respaldadas.

