---
sidebar: sidebar 
permalink: br-start-discover-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, workloads, protect 
summary: NetApp Backup and Recovery primero debe descubrir las cargas de trabajo para poder protegerlas. 
---
= Descubra las cargas de trabajo KVM en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery necesita descubrir hosts KVM y máquinas virtuales antes de protegerlos. Sus hosts KVM y máquinas virtuales deben estar administrados por una plataforma de administración como Apache CloudStack antes de poder agregarlos a Backup and Recovery.

*Rol de consola requerido* Superadministrador de Copia de seguridad y recuperación.  Conozca más sobrelink:reference-roles.html["Roles y privilegios de copia de seguridad y recuperación"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^] .



== Agregue una plataforma de administración, un host KVM y descubra recursos

Agregue la plataforma de administración y la información del host KVM y deje que NetApp Backup and Recovery descubra las cargas de trabajo.

.Pasos
. Desde el menú de la NetApp Console , seleccione *Protección > Copia de seguridad y recuperación*.
. En *Cargas de trabajo*, seleccione el mosaico *KVM*.
+
Si inicia sesión en Backup and Recovery por primera vez y tiene un sistema en la consola pero no ha descubierto ningún recurso, aparecerá la página _Bienvenido a la nueva NetApp Backup and Recovery_ con una opción para *Descubrir recursos*.

. Seleccione *Descubrir recursos*.
. Introduzca la siguiente información:
+
.. *Tipo de carga de trabajo*: Seleccione *KVM*.
.. Si aún no ha integrado su plataforma de administración con Backup and Recovery, seleccione *Agregar plataforma de administración*.
+
... Introduzca la siguiente información:
+
**** *Dirección IP o FQDN de la plataforma de administración*: ingrese la dirección IP o el nombre de dominio completo de la plataforma de administración.
**** *Clave API*: Ingrese la clave API que se utilizará para autenticar las solicitudes API.
**** *Clave secreta*: Ingrese la clave secreta que se utilizará para autenticar las solicitudes de API.
**** *Puerto*: Ingrese el puerto que se utilizará para la comunicación entre Backup and Recovery y la plataforma de administración.
**** *Agentes*: seleccione un agente de consola para utilizar para facilitar la comunicación entre Backup and Recovery y la plataforma de administración.


... Cuando haya terminado, seleccione *Agregar*.


.. *Configuración de KVM*: agregue un nuevo host KVM ingresando la siguiente información:
+
*** *FQDN o dirección IP de KVM*: ingrese el FQDN o la dirección IP del host.
*** *Credenciales*: Ingrese el nombre de usuario y la contraseña para el host KVM.
*** *Agente de consola*: elija el agente de consola que se utilizará para la comunicación entre Backup and Recovery y el host KVM.
*** *Número de puerto*: Ingrese el puerto que se utilizará para la comunicación entre Backup and Recovery y el host KVM.
*** *Plataforma de administración*: si el host KVM está administrado y ha agregado la plataforma de administración a Copia de seguridad y recuperación, seleccione la plataforma de administración de la lista.




. Seleccione *Descubrir*.
+

TIP: Este proceso puede tardar unos minutos.



.Resultado
La carga de trabajo de KVM se muestra en la lista de cargas de trabajo en la página Inventario.



== Continuar al panel de control de NetApp Backup and Recovery

.Pasos
. Desde el menú de la NetApp Console , seleccione *Protección* > *Copia de seguridad y recuperación*.
. Seleccione un mosaico de carga de trabajo (por ejemplo, Microsoft SQL Server).
. Desde el menú Copia de seguridad y recuperación, seleccione *Panel de control*.
. Revisar la salud de la protección de datos.  La cantidad de cargas de trabajo en riesgo o protegidas aumenta según las cargas de trabajo recientemente descubiertas, protegidas y respaldadas.

