---
sidebar: sidebar 
permalink: br-start-discover-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Hyper-V, workloads, protect 
summary: NetApp Backup and Recovery debe descubrir las máquinas virtuales Hyper-V antes de poder protegerlas. 
---
= Descubra las cargas de trabajo de Hyper-V en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubre las máquinas virtuales de Hyper-V en NetApp Backup and Recovery para que puedas protegerlas con políticas de protección.

*Rol de consola obligatorio* Superadministrador de Backup and Recovery. Más información sobre link:reference-roles.html["Funciones y privilegios de backup y recuperación"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].



[[add-a-hyper-v-host-and-discover-resources]]
== Agregue un host Hyper-V y descubra recursos

Agrega la información del host de Hyper-V para que NetApp Backup and Recovery pueda descubrir máquinas virtuales. Dentro de cada agente de Console, selecciona los sistemas donde quieres descubrir recursos.


NOTE: Cuando agrega hosts Hyper-V y descubre recursos, NetApp Backup and Recovery instala el complemento NetApp Hyper-V y el complemento NetApp SnapCenter Windows FileSystem en el host Hyper-V para ayudar con la administración y protección de máquinas virtuales.

.Pasos
. En el menú de la NetApp Console, selecciona *Protección* > *Backup and Recovery*.
+
Si es la primera vez que inicias sesión en NetApp Backup and Recovery y ya tienes un sistema en la Console pero aún no has descubierto recursos, aparecerá la página de inicio "Bienvenido a la nueva NetApp Backup and Recovery" con una opción para *Descubrir recursos*.

. Seleccione *Descubrir recursos*.
. Introduzca la siguiente información:
+
.. *Tipo de carga de trabajo*: seleccione *Hyper-V*.
.. Si aún no ha almacenado las credenciales para este host de Hyper-V, seleccione *Agregar credenciales*.
+
... Seleccione el agente de consola que se utilizará con este host.
... Introduzca un nombre para esta credencial.
... Introduzca el nombre de usuario y la contraseña de la cuenta.
... Seleccione *Listo*.


.. *Registro de host*: Agregue un nuevo host Hyper-V ingresando el FQDN o la dirección IP del host, las credenciales, el agente de consola y el número de puerto. Si el agente de la consola no puede resolver el FQDN, utilice la dirección IP en su lugar. Para los clústeres FCI, introduzca la dirección IP de gestión del clúster FCI.


. Seleccione *Descubrir*.
+

TIP: Este proceso puede tardar unos minutos.



.Resultado
Una vez que NetApp Backup and Recovery descubre recursos, la página Inventario muestra la carga de trabajo de Hyper-V en la lista de cargas de trabajo.



[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Continuar al panel de control de NetApp Backup and Recovery

.Pasos
. En el menú de la NetApp Console, selecciona *Protección* > *Backup and Recovery*.
. Selecciona el mosaico de la carga de trabajo de Hyper-V.
. Desde el menú Copia de seguridad y recuperación, seleccione *Panel de control*.
. Revisar la salud de la protección de datos.  La cantidad de cargas de trabajo en riesgo o protegidas aumenta según las cargas de trabajo recientemente descubiertas, protegidas y respaldadas.

