---
sidebar: sidebar 
permalink: br-use-oracle-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Puede proteger máquinas virtuales de Oracle desde sistemas ONTAP locales hasta Amazon Web Services, Microsoft Azure, Google Cloud Platform y StorageGRID, garantizando así que sus datos estén protegidos. 
---
= Descripción general de las cargas de trabajo de Protect Oracle Database
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteja las bases de datos y los registros de Oracle con NetApp Backup and Recovery.  Obtenga copias de seguridad y restauraciones rápidas, que ahorran espacio, son consistentes con las bases de datos y no presentan fallos.  Realice copias de seguridad de cargas de trabajo de Oracle en AWS S3, NetApp StorageGRID, Azure Blob Storage o ONTAP S3.  Restaurar copias de seguridad en un host Oracle local.

Utilice NetApp Backup and Recovery para implementar una estrategia de protección 3-2-1, donde tendrá 3 copias de sus datos de origen en 2 sistemas de almacenamiento diferentes junto con 1 copia en la nube. Los beneficios del enfoque 3-2-1 incluyen:

* Múltiples copias de datos protegen contra amenazas cibernéticas internas y externas.
* El uso de diferentes tipos de medios le ayudará a recuperarse si uno de ellos falla.
* Puede restaurar rápidamente desde la copia local y utilizar las copias externas si la copia local se ve comprometida.



NOTE: Para cambiar entre las versiones de la interfaz de usuario de NetApp Backup and Recovery , consultelink:br-start-switch-ui.html["Cambiar a la interfaz de usuario anterior de NetApp Backup and Recovery"] .

Puede utilizar NetApp Backup and Recovery para realizar las siguientes tareas relacionadas con las cargas de trabajo de Oracle:

* link:br-start-discover-oracle.html["Descubra las cargas de trabajo de Oracle"]
* link:br-use-oracle-protection-groups.html["Crear y administrar grupos de protección para cargas de trabajo de Oracle"]
* link:br-use-oracle-backup.html["Realizar copias de seguridad de las cargas de trabajo de Oracle"]
* link:br-use-oracle-restore.html["Restaurar cargas de trabajo de Oracle"]

