---
sidebar: sidebar 
permalink: br-use-vmware-restore-guest-files-and-folders-overview.html 
keywords:  
summary: 'Puede restaurar archivos o carpetas desde un disco de máquina virtual (VMDK) en un sistema operativo invitado Windows.' 
---
= Requisitos para la restauración de archivos invitados de VMware en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utiliza la función de restauración de archivos del sistema invitado para restaurar archivos o carpetas del disco de una máquina virtual (VMDK) en un sistema operativo invitado Windows o Linux.



[[guest-file-restore-workflow]]
== Flujo de trabajo para la restauración de archivos de invitados

La restauración de archivos de invitado incluye los siguientes pasos:

. Adjuntar
+
Conecta un disco virtual a una máquina virtual huésped o proxy y comienza una sesión de restauración de archivos huésped.

. Esperar
+
Espere a que se complete la operación de conexión antes de poder explorar y restaurar. Cuando finaliza la operación de conexión, se crea automáticamente una sesión de restauración de archivos invitados.

. Seleccionar archivos o carpetas
+
Examina o busca los archivos del disco virtual y selecciona uno o varios archivos o carpetas para restaurar.

. Restaurar
+
Restaurar los archivos o carpetas seleccionados a una ubicación específica.





[[prerequisites-for-restoring-guest-files-and-folders]]
== Requisitos previos para restaurar archivos y carpetas de invitados

Revisa todos los requisitos antes de restaurar archivos o carpetas desde un VMDK.

* El puerto 443 (HTTPS) en el servidor VMware ESXi debe estar abierto para la comunicación bidireccional.
* VMware Tools debe estar instalado en el sistema operativo invitado y en ejecución.
+
NetApp Backup and Recovery utiliza información de VMware Tools para establecer una conexión con el sistema operativo invitado de VMware.

* Debe conocer la instantánea de respaldo y el VMDK desde donde restaurar.
* El disco virtual que conectes debe estar en un backup de NetApp Backup and Recovery.
+
El disco virtual que contiene el archivo o la carpeta que desea restaurar debe estar en una copia de seguridad de VM realizada con NetApp Backup and Recovery.

* Para usar una máquina virtual proxy, la máquina virtual proxy debe estar configurada.
+
Si quieres adjuntar un disco virtual a una VM proxy, la VM proxy debe estar configurada antes de que comience la operación de adjuntar y restaurar.

* En el caso de los archivos cuyos nombres contengan caracteres que no sean del alfabeto inglés, debes restaurarlos en un directorio, no como un único archivo.
+
Puedes restaurar archivos con caracteres que no sean del alfabeto inglés, como los kanji japoneses, restaurando el directorio en el que se encuentran los archivos.



Para obtener la información más reciente sobre la compatibilidad con sistemas operativos invitados, consulta la  https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp (IMT)"^].



[[windows-guests]]
=== Invitados de Windows

* El sistema operativo invitado Windows debe ejecutar Windows Server 2008 R2 o posterior.
+
Para obtener la información más reciente sobre las versiones compatibles, consulte https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp (IMT)"^] .

* Las credenciales para la máquina virtual de destino utilizan el dominio integrado o la cuenta de administrador local con el nombre de usuario "Administrador". Antes de iniciar la operación de restauración, configure las credenciales de la máquina virtual donde desea conectar el disco virtual. Se requieren credenciales tanto para las operaciones de conexión como para las de restauración. Los usuarios del grupo de trabajo pueden utilizar la cuenta de administrador local incorporada.
+

IMPORTANT: Si debe utilizar una cuenta que no es la cuenta de administrador integrada, pero tiene privilegios administrativos dentro de la VM, debe deshabilitar UAC en la VM invitada.





[[linux-guests]]
=== Huéspedes Linux

* Se admiten las siguientes distribuciones de SO huésped:
+
** Red Hat Enterprise Linux
** Ubuntu
** Debian


* La cuenta Run-As necesita permisos de root o sudo.
* Para la restauración entre máquinas virtuales (restaurar en una máquina virtual Linux diferente), SSH debe estar ejecutándose en la máquina virtual de destino.




[[guest-file-restore-limitations]]
== Limitaciones de restauración de archivos de invitados

Antes de restaurar un archivo o una carpeta desde un sistema operativo invitado, ten en cuenta estas limitaciones.

* No se pueden restaurar tipos de discos dinámicos dentro de un sistema operativo invitado.
* Si restaura un archivo o una carpeta cifrados, el atributo de cifrado no se conserva.
* No se pueden restaurar archivos o carpetas en una carpeta cifrada.
* Los archivos y carpetas ocultos se muestran en la página de exploración de archivos y no es posible filtrarlos.
* No se pueden restaurar archivos o carpetas entre huéspedes con sistemas operativos diferentes (cuando se restaura a una máquina virtual diferente, el tipo de sistema operativo de destino debe ser el mismo que el tipo de sistema operativo de origen).
* No puedes restaurar desde un sistema de archivos NTFS a un sistema de archivos FAT.
+
Cuando intenta restaurar del formato NTFS al formato FAT, el descriptor de seguridad NTFS no se copia porque el sistema de archivos FAT no admite los atributos de seguridad de Windows.

* No es posible restaurar archivos invitados desde un VMDK clonado o un VMDK no inicializado.
* No se puede restaurar la estructura de directorio de un archivo.
+
Cuando se restaura un archivo de un directorio anidado, el sistema restaura solo el archivo, no su estructura de directorio. Para restaurar todo el árbol de directorios, copie el directorio de nivel superior.

* No es posible restaurar archivos invitados desde una máquina virtual vVol a un host alternativo.
* No es posible restaurar archivos de invitados cifrados.

