---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, on-premises, applications, virtual machines, backup and recovery 
summary: Protege los datos de tu aplicación Microsoft SQL Server desde sistemas ONTAP locales hasta Amazon Web Services, Microsoft Azure o StorageGRID usando NetApp Backup and Recovery. 
---
= Protege las cargas de trabajo de Microsoft SQL Server con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Haz backup de las bases de datos de Microsoft SQL Server desde sistemas ONTAP locales a AWS, Azure o StorageGRID usando NetApp Backup and Recovery. Implementa una estrategia de backup 3-2-1 con snapshots en el almacenamiento principal, replicación al almacenamiento secundario y copias en el almacén de objetos.

NetApp Backup and Recovery utiliza NetApp SnapMirror para sincronizar copias de seguridad creando instantáneas y transfiriéndolas a las ubicaciones de copia de seguridad.

Utiliza los siguientes flujos de trabajo para proteger tus datos:

* link:concept-start-prereq-snapcenter-import.html["Configurar elementos adicionales si se importa desde SnapCenter"]
* link:br-start-discover.html["Descubra las cargas de trabajo de Microsoft SQL Server y, opcionalmente, importe recursos de SnapCenter"]
* link:br-use-mssql-backup.html["Realice copias de seguridad de las cargas de trabajo con instantáneas locales en el almacenamiento principal local de ONTAP"]
* link:br-use-mssql-backup.html["Replicar cargas de trabajo al almacenamiento secundario de ONTAP"]
* link:br-use-mssql-backup.html["Realizar copias de seguridad de las cargas de trabajo en una ubicación de almacenamiento de objetos"]
* link:br-use-mssql-backup.html["Realice copias de seguridad de las cargas de trabajo ahora"]
* link:br-use-mssql-restore.html["Restaurar cargas de trabajo"]
* link:br-use-mssql-clone.html["Clonar cargas de trabajo"]
* link:br-use-manage-inventory.html["Gestionar inventario de cargas de trabajo"]
* link:br-use-manage-snapshots.html["Administrar instantáneas"]


Para realizar copias de seguridad de las cargas de trabajo, se crean políticas que administran las operaciones de copia de seguridad y restauración. Verlink:br-use-policies-create.html["Crear políticas"] Para más información.

.Destinos de copia de seguridad admitidos
NetApp Backup and Recovery admite backups de instancias y bases de datos de Microsoft SQL Server desde los siguientes sistemas de origen hacia los sistemas secundarios y almacenes de objetos indicados en la lista, tanto en nubes públicas como privadas. Las instantáneas permanecen en el sistema de origen.

[cols="33,33,33"]
|===
| Sistema fuente | Sistema secundario (replicación) | Almacén de objetos de destino (backup) 


| Cloud Volumes ONTAP en AWS | Cloud Volumes ONTAP en el sistema ONTAP local de AWS | Amazon S3 ONTAP S3 


| Cloud Volumes ONTAP en Azure | Cloud Volumes ONTAP en el sistema ONTAP local de Azure | Azure Blob ONTAP S3 


| Sistema ONTAP local | Cloud Volumes ONTAP Sistema ONTAP local | Amazon S3 Azure Blob StorageGRID NetApp GRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | N / A 
|===
.Destinos de restauración admitidos
Puedes restaurar instancias y bases de datos de Microsoft SQL Server a partir de un backup que se encuentre en el almacenamiento primario, en un sistema secundario (volumen replicado) o en un almacén de objetos (archivo de backup) en los siguientes sistemas de destino. Las snapshots residen en el sistema de origen y solo pueden restaurarse en ese mismo sistema.

[cols="33,33,33"]
|===
2+| Desde la ubicación del archivo de backup | Al sistema de destino 


| *Almacén de objetos (backup)* | *Sistema secundario (replicación)* |  


| Amazon S3 | Cloud Volumes ONTAP en el sistema ONTAP local de AWS | Cloud Volumes ONTAP en AWS sistema ONTAP local ONTAP S3 


| Blob de Azure | Cloud Volumes ONTAP en el sistema ONTAP local de Azure | Cloud Volumes ONTAP en Azure Sistema ONTAP local ONTAP S3 


| StorageGRID | Cloud Volumes ONTAP Sistema ONTAP local | Sistema ONTAP local ONTAP S3 
|===

NOTE: Las referencias a "sistemas ONTAP locales" incluyen los sistemas FAS y AFF .
