---
sidebar: sidebar 
permalink: br-use-restore-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: NetApp Backup and Recovery le permite restaurar aplicaciones que haya protegido con una política de protección. 
---
= Restaura aplicaciones de Kubernetes usando la interfaz web
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery le permite restaurar aplicaciones que haya protegido con una política de protección. Para restaurar una aplicación, esta debe tener al menos un punto de restauración disponible. Un punto de restauración puede ser la instantánea local o la copia de seguridad en el almacén de objetos (o ambas). Puede restaurar una aplicación utilizando el archivo local, secundario o del almacén de objetos.

.Antes de empezar
Si vas a restaurar una aplicación que se respaldó usando Trident Protect, asegúrate de que Trident Protect esté instalado tanto en el clúster de origen como en el clúster de destino.

.Rol de NetApp Console requerido
Administrador de la organización o administrador de SnapCenter . link:reference-roles.html["Obtenga información sobre los roles de acceso de NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^] .

.Pasos
. En el menú NetApp Backup and Recovery, selecciona *Restaurar*.
. Elige una aplicación de Kubernetes de la lista y selecciona *Ver y restaurar* para esa aplicación.
+
Aparece la lista de puntos de restauración.

. Selecciona el botón *Restaurar* para el punto de restauración que quieras usar.


[discrete]
===== Configuración general

. Elige la ubicación de origen desde la que quieres restaurar.
. Seleccione el clúster de destino de la lista *Clúster*.
+

NOTE: Restaurar una instantánea local creada por Trident Protect en un clúster diferente no es compatible en este momento.

. Elige restaurar en los espacios de nombres originales o en nuevos espacios de nombres.
. Si elegiste restaurar en nuevos espacios de nombres, introduce el espacio o los espacios de nombres de destino que vas a usar.
. Seleccione *Siguiente*.


[discrete]
===== Selección de recursos

. Elija si desea restaurar todos los recursos asociados con la aplicación o utilizar un filtro para seleccionar recursos específicos para restaurar:


[role="tabbed-block"]
====
.Restaurar todos los recursos
--
. Seleccione *Restaurar todos los recursos*.
. Seleccione *Siguiente*.


--
.Restaurar recursos específicos
--
. Seleccione *Recursos selectivos*.
. Elija el comportamiento del filtro de recursos.  Si elige *Incluir*, se restaurarán los recursos que seleccione.  Si elige *Excluir*, los recursos que seleccione no se restaurarán.
. Seleccione *Agregar reglas* para agregar reglas que definan filtros para seleccionar recursos.  Necesita al menos una regla para filtrar recursos.
+
Cada regla puede filtrar según criterios como el espacio de nombres del recurso, las etiquetas, el grupo, la versión y el tipo.

. Seleccione *Guardar* para guardar cada regla.
. Cuando haya agregado todas las reglas que necesita, seleccione *Buscar* para ver los recursos disponibles en el archivo de respaldo que coinciden con sus criterios de filtro.
+

NOTE: Los recursos que se muestran son los recursos que existen actualmente en el clúster.

. Cuando esté satisfecho con los resultados, seleccione *Siguiente*.


--
====
[discrete]
===== Configuración de destino

. Expande la sección *Configuración de destino* y elige restaurar a la clase de almacenamiento predeterminada, a una clase de almacenamiento diferente o, si estás restaurando a un clúster diferente, asignar las clases de almacenamiento al clúster de destino.
. Si elegiste restaurar en una clase de almacenamiento diferente, selecciona una clase de almacenamiento de destino que coincida con cada clase de almacenamiento de origen.
. Opcionalmente, si estás restaurando una copia de seguridad o una instantánea que se hizo usando Trident Protect, revisa los detalles del AppVault usado como bucket de almacenamiento para la operación de restauración. Si hay un cambio en tu entorno o en el estado de AppVault, selecciona *Sync App Vault* para actualizar los detalles.
+

NOTE: Si necesitas crear un AppVault en un clúster de Kubernetes para facilitar la restauración de una copia de seguridad o instantánea creada usando Trident Protect, consulta https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-appvault-custom-resources.html["Usa los objetos de Trident Protect AppVault para gestionar buckets"].

. Opcionalmente, expande la sección *Restore scripts* y habilita la opción *Postscript* para elegir una plantilla de hook de ejecución que se ejecutará después de que la operación de restauración haya terminado. Si lo necesitas, introduce cualquier argumento que el script necesite y añade selectores de etiquetas para filtrar recursos según las etiquetas de los recursos.
. Seleccione *Restaurar*.

