---
sidebar: sidebar 
permalink: br-use-mssql-restore-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Las copias de seguridad de sus datos están disponibles para restaurar desde las ubicaciones donde creó las copias de seguridad, lo que incluye instantáneas, replicaciones y copias de seguridad en el almacenamiento de objetos.  Revise las ubicaciones de restauración, los puntos de restauración y los tipos de recursos para restaurar. 
---
= Descripción general de la restauración de cargas de trabajo de Microsoft SQL mediante NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las copias de seguridad de los datos de Microsoft SQL Server de NetApp Backup and Recovery están disponibles para restaurar desde las ubicaciones donde movió las copias de seguridad: instantáneas, replicaciones o copias de seguridad en el almacenamiento de objetos.  Puede restaurar una carga de trabajo en el sistema original, en un sistema diferente que use la misma cuenta en la nube o en un sistema ONTAP local.  Revise las ubicaciones de restauración, los puntos de restauración y los tipos de recursos para restaurar.

.Restaurar desde estas ubicaciones
Puede restaurar cargas de trabajo desde diferentes ubicaciones de inicio:

* Restaurar desde una ubicación principal
* Restaurar desde un recurso replicado
* Restaurar desde una copia de seguridad del almacén de objetos


.Restaurar a estos puntos
Puede restaurar datos a la última instantánea o a estos puntos:

* Restaurar desde instantáneas
* Restaurar a un punto específico en el tiempo.  Esto es útil si conoce el nombre y la ubicación del archivo, y la fecha en la que estuvo en buen estado por última vez.
* Restaurar a la última copia de seguridad




== ¿Qué sigue?

Para obtener detalles sobre cómo restaurar cargas de trabajo, consultelink:br-use-mssql-restore.html["Restaurar cargas de trabajo"] .
