---
sidebar: sidebar 
permalink: br-use-oracle-restore.html 
keywords: restore, vm, oracle, databases, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Protege tus cargas de trabajo de Oracle Database con NetApp Backup and Recovery. 
---
= Restaura cargas de trabajo de bases de datos Oracle con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Restaura cargas de trabajo de bases de datos Oracle desde instantáneas, backups replicados en almacenamiento secundario o backups almacenados en un almacén de objetos usando NetApp Backup and Recovery.

.Restaurar desde estas ubicaciones
Puede restaurar bases de datos desde diferentes ubicaciones de inicio:

* Restaurar desde una ubicación principal (instantánea local)
* Restaurar desde un recurso replicado en un almacenamiento secundario
* Restaurar desde una copia de seguridad de almacenamiento de objetos


.Restaurar a estos puntos
Puede restaurar datos a la ubicación original; la restauración a una ubicación alternativa no está disponible en esta versión preliminar privada.

* Restaurar a la ubicación original




[[how-oracle-database-restore-works]]
== Cómo funciona la restauración de Oracle Database

Al restaurar cargas de trabajo de Oracle Database, ocurre lo siguiente:

* Cuando restaura una base de datos desde una instantánea local, NetApp Backup and Recovery crea un _nuevo_ recurso utilizando los datos de la copia de seguridad.
* Al restaurar desde un almacenamiento replicado, puede restaurarlo a la ubicación original.
* Cuando restaura una copia de seguridad desde el almacenamiento de objetos, puede restaurar los datos en el almacenamiento de origen o en un sistema ONTAP local y recuperar la base de datos desde allí.


Desde la página Restaurar (también conocida como Buscar y restaurar), puede restaurar una base de datos, incluso si no recuerda el nombre exacto, la ubicación en la que se encuentra o la fecha en la que estuvo en buen estado por última vez.  Puede buscar en la base de datos utilizando filtros.



[[restore-an-oracle-database]]
== Restaurar una base de datos Oracle

En función de tus necesidades, puedes restaurar una base de datos Oracle a un momento específico, a un número de cambio del sistema (SCN) específico o al último estado válido. También puedes restaurar la base de datos a partir de instantáneas y omitir el proceso de recuperación automático, por ejemplo, si quieres realizar la recuperación manualmente. Puedes buscar la base de datos usando su nombre o con filtros específicos.

*Rol requerido de NetApp Console*: superadministrador de NetApp Backup and Recovery o administrador de restauración de NetApp Backup and Recovery. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].

[NOTE]
====
Si restauras PDB o espacios de tabla a un momento específico o a un SCN:

* Selecciona solo un PDB. La recuperación a un momento específico no es compatible con restaurar varios PDB.
* `PDB$SEED` No se puede seleccionar para recuperación a un momento específico.
* La restauración de archivos de control no se puede combinar con la recuperación a un momento específico de los PDB o de los espacios de tabla de los PDB.
* Asegúrate de que el backup de datos y los backups de registros necesarios estén catalogados.
* Los espacios de tabla  `SYSTEM`,  `SYSAUX` y  `UNDO` no se pueden seleccionar.
* Comprueba que el backup de datos y los backups de registros necesarios estén catalogados.


====
.Pasos
. Desde el menú de la NetApp Console , seleccione *Protección > Copia de seguridad y recuperación*.
. Desde el menú de NetApp Backup and Recovery , seleccione *Restaurar*.
. En la lista desplegable a la derecha del campo de búsqueda de nombre, seleccione *Oracle*.
. Ingrese el nombre de la base de datos que desea restaurar o filtre por el host de la base de datos donde se encuentra la base de datos que desea restaurar.
+
Aparecerá una lista de instantáneas que coinciden con sus criterios de búsqueda.

. Seleccione el botón *Restaurar* para la base de datos que desea restaurar.
. Elija una opción de restauración:
+
[role="tabbed-block"]
====
.Restaurar a un punto específico en el tiempo
--
.. Seleccione *Restaurar a un punto específico en el tiempo*.
.. Seleccione *Siguiente*.
.. Elija una fecha del menú desplegable y seleccione *Buscar*.
+
Se muestra la instantánea más cercana a la fecha y hora especificadas.

.. Si lo deseas, selecciona *Ver copias de seguridad de los registros* para ver las copias de seguridad de los registros correspondientes.
+
... Comprueba que los backups de los registros estén montados.


.. Si la instantánea está almacenada en más de una ubicación, selecciona una ubicación de origen para usar y añade o revisa los detalles de la ubicación.
.. Seleccione *Siguiente*.


--
.Restaurar a un número de cambio de sistema específico (SCN)
--
.. Seleccione *Restaurar a un número de cambio de sistema específico (SCN)*.
.. Seleccione *Siguiente*.
.. Ingrese el SCN que se utilizará como punto de restauración y seleccione *Buscar*.
+
Se muestra la instantánea más cercana para el SCN especificado.

.. Si lo deseas, selecciona *Ver copias de seguridad de los registros* para ver las copias de seguridad de los registros correspondientes.
+
... Comprueba que los backups de los registros estén montados.


.. Si la instantánea está almacenada en más de una ubicación, selecciona una ubicación de origen para usar y añade o revisa los detalles de la ubicación.
.. Seleccione *Siguiente*.


--
.Restaurar a la última copia de seguridad (último estado correcto)
--
.. Seleccione *Restaurar a la última copia de seguridad*.
.. Seleccione *Siguiente*.
+
Se muestra la última instantánea. La operación de restauración recupera el último estado válido usando todos los backups de registro disponibles.

.. Si lo deseas, selecciona *Ver copias de seguridad de los registros* para ver las copias de seguridad de los registros correspondientes.
+
... Comprueba que los backups de los registros estén montados.


.. Si la instantánea está almacenada en más de una ubicación, selecciona una ubicación de origen para usar y añade o revisa los detalles de la ubicación.
.. Seleccione *Siguiente*.


--
.Restaurar desde instantáneas sin recuperación
--
.. Seleccione *Restaurar desde instantáneas sin recuperación*.
+
Al seleccionar esta opción, la base de datos se restaurará a partir de instantáneas, pero se omitirá la recuperación (no se aplicarán los backups de registros).

.. Seleccione *Siguiente*.
+
Se muestran las instantáneas disponibles.

.. Selecciona una instantánea de la lista y selecciona *Siguiente*.
.. Si la instantánea está almacenada en más de una ubicación, selecciona una ubicación de origen para usar y añade o revisa los detalles de la ubicación.
.. Seleccione *Siguiente*.


--
====
. Elija el destino de restauración y la configuración:
+
[role="tabbed-block"]
====
.Restaurar a la ubicación original
--
.. En la sección *Configuración de destino*, haz lo siguiente:
+
... En el caso de las bases de datos RAC, selecciona el nodo RAC en el que se va a ejecutar la restauración. Esta opción solo aparece para las bases de datos RAC.
... Selecciona lo que quieres restaurar:
+
**** Selecciona *Todos los archivos de datos* para restaurar toda la base de datos o la base de datos contenedora (CDB).
**** Selecciona *Bases de datos conectables (PDBs)* para restaurar una o varias PDBs desde una CDB sin afectar a las demás PDBs del contenedor. Luego selecciona las PDBs de la lista.
**** Selecciona *Espacios de tabla de base de datos conectables (PDB)* (que aparecen como *Espacios de tabla* en una base de datos que no sea CDB) para restaurar espacios de tabla PDB específicos. Luego, selecciona la PDB y los espacios de tabla.


... Si lo deseas, activa la opción *Archivos de control* para restaurar también los archivos de control de la base de datos. Esta opción no se puede seleccionar para la recuperación a un momento específico o por SCN de PDB o espacios de tabla de PDB.
... Si lo deseas, activa la opción *Cambiar el estado de la base de datos si es necesario para la restauración y la recuperación* para permitir que NetApp Backup and Recovery gestione el estado de la base de datos según el tipo de recuperación.
... Si lo deseas, activa la opción *Restaurar sin movimiento* para realizar una restauración sin movimiento cuando se hayan añadido nuevos archivos de datos después del backup, o cuando se hayan añadido, eliminado o vuelto a crear LUN en un grupo de discos LVM. Esto anula la comprobación de archivos externos; la recuperación de bases de datos continúa usando la opción de restauración que seleccionaste.
... Especifica las ubicaciones de los archivos de registro de archivo externo en el campo *Ubicaciones de los archivos de registro de archivo externo* si, al restaurar PDB o espacios de tabla a un momento específico o a un SCN, los archivos de registro de archivo externo no se encuentran en la ubicación configurada. Ingresa una ruta del sistema de archivos que comience con `/` o un grupo de discos ASM que comience con `+`. Usa los botones "más" y "menos" junto al campo de entrada de texto para agregar o quitar ubicaciones. Este campo no aparece cuando restauras desde snapshots sin recuperación.
... Si lo deseas, activa la opción *Abrir la base de datos o la base de datos contenedora en modo lectura/escritura tras la recuperación* y selecciona una subopción que se ajuste al ámbito de la restauración (estas opciones no aparecen cuando se restaura a partir de instantáneas sin recuperación):
+
**** *Todos los archivos de datos*: Abre la base de datos o la base de datos contenedora en modo lectura/escritura tras la recuperación.
**** *PDB o espacios de tabla PDB*: Abre las bases de datos conectables en modo lectura/escritura tras la recuperación.
**** *Espacios de tabla que no pertenecen al CDB*: Pon los espacios de tabla en línea después de la recuperación.




.. En la sección *Prescripts y postscripts*, haz lo siguiente:
+
... *Prescript*: Si lo deseas, activa esta opción e introduce la ruta completa de un script que debe ejecutarse antes de la operación de restauración y cualquier argumento que requiera dicho script.
... *Posdata*: Opcionalmente, habilite esta opción e ingrese la ruta completa de un script que debe ejecutarse después de la operación de restauración y cualquier argumento que tome el script.
... Elige un valor de tiempo de espera para el script. Si el script no se ejecuta dentro de este plazo, la restauración se llevará a cabo de todos modos.




--
.Restaurar a una ubicación alternativa
--
No está disponible para cargas de trabajo de Oracle Database en esta versión preliminar.

--
====
. Seleccione *Restaurar*.

