---
sidebar: sidebar 
permalink: br-use-hyperv-restore.html 
keywords: restore, vm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, Amazon Web services, AWS, NetApp Backup and Recovery 
summary: Proteja sus cargas de trabajo de Hyper-V con NetApp Backup and Recovery. 
---
= Restaure cargas de trabajo de Hyper-V con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Restaura cargas de trabajo de Hyper-V desde instantáneas locales, backups replicados en almacenamiento secundario o backups en almacén de objetos usando NetApp Backup and Recovery.

.Restaurar desde estas ubicaciones
Puedes restaurar cargas de trabajo desde estas ubicaciones:

* Restaurar desde una ubicación principal (instantánea local)
* Restaurar desde un recurso replicado en un almacenamiento secundario
* Restaurar desde una copia de seguridad de almacenamiento de objetos


.Restaurar a estos puntos
Puedes restaurar datos en estos destinos:

* Restaurar en la ubicación original (desde almacenamiento primario, secundario y almacén de objetos)
* Restaurar en una ubicación alternativa (desde el almacenamiento primario, secundario y de objetos)


.Consideraciones sobre la restauración desde el almacenamiento de objetos
Si seleccionas un archivo de backup en el almacén de objetos y la protección contra ransomware está activa para ese backup porque habilitaste DataLock y la protección contra ransomware en la política de backup, se te pedirá que realices una comprobación de integridad adicional antes de restaurar los datos. Te recomendamos que realices el análisis.


TIP: Incurrirá en costos de salida adicionales de su proveedor de nube para acceder al contenido del archivo de respaldo.



[[how-restoring-workloads-works]]
== Cómo funciona la restauración de cargas de trabajo

Al restaurar una carga de trabajo, ocurre lo siguiente:

* Cuando restaura una carga de trabajo desde un archivo de respaldo local, NetApp Backup and Recovery crea un _nuevo_ recurso utilizando los datos del respaldo.
* Al restaurar desde una carga de trabajo replicada, puede restaurar la carga de trabajo en el sistema original o en un sistema ONTAP local.


Desde la página «Restaurar», puedes restaurar un recurso aunque no recuerdes su nombre exacto, su ubicación o la fecha de su última copia de seguridad válida. Puedes buscar la instantánea utilizando filtros.



[[restore-hyper-v-workloads]]
== Restaurar cargas de trabajo de Hyper-V

Restaura las cargas de trabajo de Hyper-V mediante el menú «Restaurar». Puedes buscar una instantánea por nombre o utilizando filtros.

*Rol requerido de NetApp Console*: superadministrador de NetApp Backup and Recovery o administrador de restauración de NetApp Backup and Recovery. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].

.Pasos
. Desde el menú de NetApp Backup and Recovery , seleccione *Restaurar*.
. En la lista desplegable a la derecha del campo de búsqueda de nombre, seleccione *Hyper-V*.
. Introduce el nombre del recurso que deseas restaurar o filtra por nombre de máquina virtual, host de la máquina virtual o el grupo de almacenamiento en el que se encuentra el recurso.
+
Aparecerá una lista de instantáneas que coinciden con sus criterios de búsqueda.

. Seleccione el botón *Restaurar* para la instantánea que desea restaurar.
+
Aparece una lista de posibles puntos de restauración.

. Seleccione el punto de restauración que desea utilizar.
. Seleccione una ubicación de origen de la instantánea.
. Seleccione *Siguiente* para continuar.
. Elija el destino de restauración y la configuración:
+
[discrete]
===== Selección de destino

+
[role="tabbed-block"]
====
.Restaurar a la ubicación original
--
.. Selecciona el panel *Ubicación original*. Cuando restaures a la ubicación original, puedes ver la configuración de destino expandiendo la sección *Configuración de destino*, pero no puedes cambiarla.
.. En la sección *Opciones posteriores a la restauración*, considere la siguiente opción:
+
*** *Iniciar la máquina virtual*: habilite esta opción para iniciar la nueva máquina virtual después de restaurarla.




--
.Restaurar a una ubicación alternativa
--
.. Seleccione el panel *Ubicación alternativa*.
.. En la sección *Configuración de destino*, introduce la siguiente información:
+
*** *FQDN o dirección IP de Hyper-V*: ingrese el nombre de dominio completo o la dirección IP del host Hyper-V de destino.
*** *Red*: Seleccione la red de destino donde desea restaurar la instantánea.
*** *Nombre de la máquina virtual*: Ingrese el nombre de la máquina virtual que desea restaurar.
*** *Ubicación de destino*: ingrese la carpeta de destino o el recurso compartido CIFS que debe contener los datos restaurados.


.. En la sección *Almacenamiento de destino* (visible únicamente al restaurar desde un almacén de objetos):
+
*** *Cambiar la ubicación de almacenamiento predeterminada*: activa esta opción para restaurar una copia de seguridad del almacén de objetos en una ubicación diferente si no se puede acceder a la ubicación de almacenamiento de origen o si está llena. Elige un clúster, una máquina virtual de almacenamiento o un agregado diferente para usar.


.. En la sección *Pre-restore options*, ten en cuenta las siguientes opciones:
+
*** *Restauración rápida*: habilite esta opción para que la máquina virtual restaurada esté disponible de inmediato. Solo se restauran desde el almacén de objetos los archivos necesarios para ejecutar la máquina virtual, en lugar del volumen completo.


.. En la sección *Opciones tras la restauración*, ten en cuenta las siguientes opciones:
+
*** *Iniciar la máquina virtual*: habilite esta opción para iniciar la nueva máquina virtual después de restaurarla.




--
====
. Seleccione *Restaurar*.

