---
sidebar: sidebar 
permalink: br-use-manage-execution-hook-templates.html 
keywords: hooks, execution hooks, exec hooks, hook, execution, script, postscript, prescript, post, pre, run, backup, snapshot, freeze 
summary: NetApp Backup and Recovery le permite administrar ganchos de ejecución para tomar medidas antes o después de las operaciones de protección de aplicaciones. 
---
= Administrar plantillas de gancho de ejecución de NetApp Backup and Recovery para cargas de trabajo de Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un gancho de ejecución es una acción personalizada que se ejecuta con una operación de protección de datos en una aplicación Kubernetes administrada.  Por ejemplo, cree instantáneas consistentes con la aplicación utilizando un gancho de ejecución para pausar las transacciones de la base de datos antes de una instantánea y reanudarlas después.  Al crear una plantilla de gancho de ejecución, especifique el tipo de gancho, el script a ejecutar y los filtros para los contenedores de destino.  Utilice la plantilla para vincular ganchos de ejecución a sus aplicaciones.

[NOTE]
====
NetApp Backup and Recovery congela y descongela sistemas de archivos para aplicaciones como KubeVirt durante la protección de datos.  Puede deshabilitar este comportamiento de forma global o para aplicaciones específicas utilizando la documentación de protección de Trident :

* Para deshabilitar este comportamiento para todas las aplicaciones, consulte https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html#protecting-data-with-kubevirt-vms["Protección de datos con máquinas virtuales KubeVirt"] .
* Para deshabilitar este comportamiento para una aplicación específica, consulte https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-manage-applications.html#define-an-application["Definir una aplicación"] .


====
.Rol de NetApp Console requerido
Administrador de la organización o administrador de SnapCenter . link:reference-roles.html["Obtenga información sobre los roles de acceso de NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^] .



== Tipos de ganchos de ejecución

NetApp Backup and Recovery admite los siguientes tipos de ganchos de ejecución, según cuándo se puedan ejecutar:

* Pre-instantánea
* Post-instantánea
* Copia de seguridad previa
* Post-copia de seguridad
* Post-restauración




=== Orden de ejecución

Cuando se ejecuta una operación de protección de datos, los eventos de enlace de ejecución tienen lugar en el siguiente orden:

. Todos los ganchos de ejecución de preoperación personalizados aplicables se ejecutan en los contenedores apropiados. Puede crear varios ganchos de preoperación personalizados, pero su orden de ejecución no está garantizado ni es configurable.
. Si corresponde, se producen bloqueos del sistema de archivos.
. Se realiza la operación de protección de datos.
. Los sistemas de archivos congelados se descongelan, si corresponde.
. NetApp Backup and Recovery ejecuta cualquier gancho de ejecución previo a la operación personalizado aplicable en los contenedores apropiados.  Puede crear varios ganchos posteriores a la operación personalizados, pero su orden de ejecución no está garantizado ni es configurable.


Si crea varios ganchos del mismo tipo, no se garantiza su orden de ejecución.  Los ganchos de diferentes tipos siempre se ejecutan en el orden especificado. Por ejemplo, el siguiente es el orden de ejecución de una configuración que tiene todos los diferentes tipos de ganchos:

. Ganchos previos a la instantánea ejecutados
. Ganchos posteriores a la instantánea ejecutados
. Ganchos de pre-copia de seguridad ejecutados
. Ganchos posteriores a la copia de seguridad ejecutados



NOTE: Pruebe los scripts de ejecución de gancho antes de habilitarlos en producción.  Utilice 'kubectl exec' para probar scripts, luego verifique las instantáneas y las copias de seguridad clonando la aplicación en un espacio de nombres temporal y restaurándola.


NOTE: Si un gancho de ejecución previo a la instantánea agrega, cambia o elimina recursos de Kubernetes, esos cambios se incluyen en la instantánea o la copia de seguridad y en cualquier operación de restauración posterior.



== Notas importantes sobre los ganchos de ejecución personalizados

Tenga en cuenta lo siguiente al planificar ganchos de ejecución para sus aplicaciones.

* Un gancho de ejecución debe utilizar un script para realizar acciones.  Muchos ganchos de ejecución pueden hacer referencia al mismo script.
* Los ganchos de ejecución deben escribirse en el formato de scripts de shell ejecutables.
* El tamaño del script está limitado a 96 KB.
* Las configuraciones de gancho de ejecución y cualquier criterio coincidente se utilizan para determinar qué ganchos son aplicables a una operación de instantánea, copia de seguridad o restauración.



NOTE: Los ganchos de ejecución pueden reducir o deshabilitar la funcionalidad de la aplicación.  Haga que sus ganchos personalizados se ejecuten lo más rápido posible. Si inicia una operación de copia de seguridad o instantánea con ganchos de ejecución asociados pero luego la cancela, los ganchos aún podrán ejecutarse si la operación de copia de seguridad o instantánea ya ha comenzado. Esto significa que la lógica utilizada en un gancho de ejecución posterior a una copia de seguridad no puede asumir que la copia de seguridad se completó.



== Filtros de gancho de ejecución

Cuando agrega o edita un gancho de ejecución para una aplicación, puede agregar filtros al gancho de ejecución para administrar con qué contenedores coincidirá el gancho.  Los filtros son útiles para las aplicaciones que utilizan la misma imagen de contenedor en todos los contenedores, pero pueden usar cada imagen para un propósito diferente (como Elasticsearch).  Los filtros le permiten crear escenarios en los que los ganchos de ejecución se ejecutan en algunos, pero no necesariamente en todos los contenedores idénticos.  Si crea varios filtros para un único gancho de ejecución, se combinan con un operador AND lógico.  Puede tener hasta 10 filtros activos por gancho de ejecución.

Cada filtro que agrega a un gancho de ejecución utiliza una expresión regular para que coincida con los contenedores en su clúster.  Cuando un gancho coincide con un contenedor, el gancho ejecutará su script asociado en ese contenedor.  Las expresiones regulares para filtros utilizan la sintaxis de Expresión regular 2 (RE2), que no admite la creación de un filtro que excluya contenedores de la lista de coincidencias.  Para obtener información sobre la sintaxis que NetApp Backup and Recovery admite para expresiones regulares en filtros de gancho de ejecución, consulte https://github.com/google/re2/wiki/Syntax["Compatibilidad con la sintaxis de expresiones regulares 2 (RE2)"^] .


NOTE: Si agrega un filtro de espacio de nombres a un gancho de ejecución que se ejecuta después de una operación de restauración o clonación y el origen y el destino de la restauración o clonación están en espacios de nombres diferentes, el filtro de espacio de nombres solo se aplica al espacio de nombres de destino.



== Ejemplos de ganchos de ejecución

Visita el https://github.com/NetApp/Verda["Proyecto NetApp Verda en GitHub"] para descargar ganchos de ejecución reales para aplicaciones populares como Apache Cassandra y Elasticsearch.  También puede ver ejemplos y obtener ideas para estructurar sus propios ganchos de ejecución personalizados.



== Crear una plantilla de gancho de ejecución

Puede crear una plantilla de gancho de ejecución personalizada que pueda utilizar para realizar acciones antes o después de una operación de protección de datos en una aplicación.

.Pasos
. En la consola, vaya a *Protección* > *Copia de seguridad y recuperación*.
. Seleccione la pestaña *Configuración*.
. Expande la sección *Plantilla de gancho de ejecución*.
. Seleccione *Crear plantilla de gancho de ejecución*.
. Introduzca un nombre para el gancho de ejecución.
. Opcionalmente, elija un tipo de enlace. Por ejemplo, un enlace posterior a la restauración se ejecuta una vez finalizada la operación.
. En el cuadro de texto *Script*, ingrese el script de shell ejecutable que desea ejecutar como parte de la plantilla de gancho de ejecución.  Opcionalmente, puede seleccionar *Cargar script* para cargar un archivo de script en su lugar.
. Seleccione *Crear*.
+
Después de crear la plantilla, ésta aparece en la lista de plantillas en la sección *Plantilla de gancho de ejecución*.


