---
sidebar: sidebar 
permalink: br-use-kvm-restore.html 
keywords: restore, vm, kvm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja sus cargas de trabajo KVM con NetApp Backup and Recovery. 
---
= Restaurar máquinas virtuales KVM con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Restaure máquinas virtuales KVM a partir de instantáneas, de una copia de seguridad de grupo de protección replicada en almacenamiento secundario o de copias de seguridad almacenadas en almacenamiento de objetos mediante NetApp Backup and Recovery.

.Restaurar desde estas ubicaciones
Puede restaurar máquinas virtuales desde diferentes ubicaciones de inicio:

* Restaurar desde una ubicación principal (instantánea local)
* Restaurar desde un recurso replicado en un almacenamiento secundario
* Restaurar desde una copia de seguridad de almacenamiento de objetos


.Restaurar a estos puntos
Puede restaurar datos en estos puntos:

* Restaurar a la ubicación original
* Restaurar a una ubicación alternativa


.Consideraciones sobre la restauración desde el almacenamiento de objetos
Si selecciona un archivo de respaldo en el almacenamiento de objetos y la protección contra ransomware está activa para ese respaldo (si habilitó DataLock y Ransomware Resilience en la política de respaldo), se le solicitará que ejecute una verificación de integridad adicional en el archivo de respaldo antes de restaurar los datos.  Le recomendamos que realice el escaneo.


TIP: Incurrirá en costos de salida adicionales de su proveedor de nube para acceder al contenido del archivo de respaldo.



== Cómo funciona la restauración de máquinas virtuales

Al restaurar máquinas virtuales, ocurre lo siguiente:

* Cuando restaura una carga de trabajo desde un archivo de respaldo local, NetApp Backup and Recovery crea un _nuevo_ recurso utilizando los datos del respaldo.
* Al restaurar desde una máquina virtual replicada, puede restaurarla en el sistema original o en un sistema ONTAP local.
* Al restaurar una copia de seguridad desde el almacenamiento de objetos, puede restaurar los datos en el sistema original o en un sistema ONTAP local.


Desde la página Restaurar, puedes restaurar una máquina virtual, incluso si no recuerdas el nombre exacto, la ubicación en la que reside o la fecha en la que estuvo en buen estado por última vez. Puedes buscar la instantánea usando filtros.



== Restaurar máquinas virtuales KVM

Restaura máquinas virtuales KVM usando el menú Restaurar. Puedes buscar la instantánea por su nombre o usando filtros.

*Rol de consola requerido* Rol de superadministrador de Backup and Recovery o rol de administrador de restauración de Backup and Recovery. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^] .

.Pasos
. Desde el menú de la NetApp Console , seleccione *Protección > Copia de seguridad y recuperación*.
. Desde el menú de NetApp Backup and Recovery , seleccione *Restaurar*.
. En la lista desplegable a la derecha del campo de búsqueda de nombre, seleccione *KVM*.
. Ingrese el nombre de la máquina virtual que desea restaurar o filtre por host de máquina virtual o grupo de almacenamiento donde se encuentra el recurso que desea restaurar.
+
Aparecerá una lista de instantáneas que coinciden con sus criterios de búsqueda.

. Seleccione el botón *Restaurar* para la instantánea que desea restaurar.
+
Aparece una lista de posibles puntos de restauración.

. Seleccione el punto de restauración que desea utilizar.
. Seleccione una ubicación de origen de la instantánea.
. Seleccione *Siguiente* para continuar.
. Elija el destino de restauración y la configuración:
+
[discrete]
===== Selección de destino

+
[role="tabbed-block"]
====
.Restaurar a la ubicación original
--
.. Seleccione el panel *Ubicación original*.
.. En la sección *Opciones posteriores a la restauración*, activa la opción *Reiniciar máquina virtual* para reiniciar la máquina virtual una vez finalizada la operación de restauración.


--
.Restaurar a una ubicación alternativa
--
.. Seleccione el panel *Ubicación alternativa*.
.. En la sección *Cloudstack settings*: proporciona la siguiente información:
+
*** *Zona*: Elige una zona de destino CloudStack de la lista.
*** *Pod*: Elige un pod de destino dentro de la zona seleccionada de la lista.
*** *Cluster*: Elige de la lista un clúster de destino dentro del pod seleccionado.
*** *Host*: Elige un host de destino en el clúster de la lista.
*** *Pool de almacenamiento*: Elige un pool de almacenamiento de destino de la lista (el volumen de destino debe estar ubicado aquí).
*** *Red*: Selecciona la red a la que se conectará la máquina virtual restaurada.
*** *Nombre de la máquina virtual*: Ingresa un nombre para la máquina virtual que se va a restaurar.
*** *Nombre para mostrar*: Ingresa el nombre que debe mostrarse para esta VM en Backup and Recovery.
*** *Ruta del pool de almacenamiento*: Ingresa la ruta del pool de almacenamiento donde se almacenarán los volúmenes VM.


.. Elige una oferta de servicio que defina tu nivel preferido de asignación de recursos de la lista *Seleccionar oferta de servicio*.
.. Activa la opción *Forced* para importar la VM restaurada aunque ya existan una o varias direcciones MAC de NIC de la VM. Si ya existe una dirección MAC, se genera una nueva dirección MAC para esa NIC.
.. En la sección *Opciones posteriores a la restauración*, considere las siguientes opciones:
+
*** *Reiniciar máquina virtual*: Activa esta opción para arrancar la nueva máquina virtual después de restaurarla.




--
====
. Seleccione *Restaurar*.

