---
sidebar: sidebar 
permalink: br-use-reports.html 
keywords: backing up, back up, backup, backup on-prem ontap, policy, policies, backup policies, cloud backup, aws, aws s3, azure, google cloud 
summary: En NetApp Backup and Recovery, cree informes para ver el estado de sus copias de seguridad, incluida la cantidad de copias de seguridad realizadas, la cantidad de copias de seguridad realizadas correctamente y la cantidad de copias de seguridad fallidas.  También puede ver los detalles de cada copia de seguridad, incluido el tipo de copia de seguridad, el sistema de almacenamiento utilizado para la copia de seguridad y la hora de la copia de seguridad. 
---
= Crea informes de protección de Microsoft SQL Server en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Crea informes para las cargas de trabajo de Microsoft SQL Server en NetApp Backup and Recovery para revisar el estado y los detalles de los backups, incluyendo el número de backups exitosos y fallidos, los tipos de backup, los sistemas de almacenamiento y las marcas de tiempo.



[[create-a-protection-report]]
== Crear un informe de protección

*Rol obligatorio de NetApp Console*: visor de almacenamiento, superadministrador de Backup and Recovery, administrador de backup de Backup and Recovery, administrador de restauración de Backup and Recovery, administrador de clonado de Backup and Recovery. Si estás protegiendo datos almacenados en un clúster de Cloud Volumes ONTAP, también se requiere el rol de Cloud Volumes ONTAP Admin. Conoce más sobre link:reference-roles.html["Roles y privilegios de copia de seguridad y recuperación"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].

.Pasos
. En el menú NetApp Backup and Recovery, selecciona *Reports*.
. Seleccione *Crear informe*.
. Introduzca los detalles del alcance del informe:
+
** *Nombre del informe*: Ingrese un nombre único para el informe.
** *Tipo de informe*: elija si desea un informe por cuenta o por carga de trabajo (Microsoft SQL Server).
** *Seleccionar host*: si seleccionó por carga de trabajo, seleccione el host para el cual desea generar el informe.
** *Seleccionar contenidos*: elija si desea que el informe incluya un resumen de todas las copias de seguridad o detalles de cada copia de seguridad.  (Si eligió "Por cuenta")


. Introduce el intervalo del informe: elige si quieres que el informe incluya datos del último día, de los últimos 7 días, de los últimos 30 días, del último trimestre o del último año.
. Introduce los datos de envío del informe: si quieres que el informe se envíe por correo electrónico, selecciona *Enviar informe por correo electrónico*. Introduce la dirección de correo electrónico a la que quieres que se envíe el informe.
+
Configura las notificaciones por correo electrónico en la página de configuración. Para obtener más información sobre cómo configurar las notificaciones por correo electrónico, consulta link:br-start-configure.html["Configurar ajustes"].


