---
sidebar: sidebar 
permalink: br-use-hyperv-restore.html 
keywords: restore, vm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, Amazon Web services, AWS, NetApp Backup and Recovery 
summary: Proteja sus cargas de trabajo de Hyper-V con NetApp Backup and Recovery. 
---
= Restaure cargas de trabajo de Hyper-V con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Restaure cargas de trabajo de Hyper-V a partir de instantáneas, de una copia de seguridad de la carga de trabajo replicada en almacenamiento secundario o de copias de seguridad almacenadas en almacenamiento de objetos mediante NetApp Backup and Recovery.

.Restaurar desde estas ubicaciones
Puede restaurar cargas de trabajo desde diferentes ubicaciones de inicio:

* Restaurar desde una ubicación principal (instantánea local)
* Restaurar desde un recurso replicado en un almacenamiento secundario
* Restaurar desde una copia de seguridad de almacenamiento de objetos


.Restaurar a estos puntos
Puede restaurar datos en estos puntos:

* Restaurar a la ubicación original
* Restaurar a una ubicación alternativa


.Consideraciones sobre la restauración desde el almacenamiento de objetos
Si selecciona un archivo de respaldo en el almacenamiento de objetos y la protección contra ransomware está activa para ese respaldo (si habilitó DataLock y Ransomware Resilience en la política de respaldo), se le solicitará que ejecute una verificación de integridad adicional en el archivo de respaldo antes de restaurar los datos.  Le recomendamos que realice el escaneo.


TIP: Incurrirá en costos de salida adicionales de su proveedor de nube para acceder al contenido del archivo de respaldo.



== Cómo funciona la restauración de cargas de trabajo

Al restaurar cargas de trabajo, ocurre lo siguiente:

* Cuando restaura una carga de trabajo desde un archivo de respaldo local, NetApp Backup and Recovery crea un _nuevo_ recurso utilizando los datos del respaldo.
* Al restaurar desde una carga de trabajo replicada, puede restaurar la carga de trabajo en el sistema original o en un sistema ONTAP local.


Desde la página Restaurar (también conocida como Buscar y restaurar), puedes restaurar un recurso, incluso si no recuerdas el nombre exacto, la ubicación en la que se encuentra o la fecha en la que estuvo en buenas condiciones por última vez. Puede buscar la instantánea utilizando filtros.



== Restaurar datos de carga de trabajo desde la opción Restaurar (Buscar y restaurar)

Restaure las cargas de trabajo de Hyper-V mediante la opción Restaurar. Puede buscar la instantánea por su nombre o utilizando filtros.

*Rol de consola requerido* Rol de superadministrador de Backup and Recovery o rol de administrador de restauración de Backup and Recovery. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^] .

.Pasos
. Desde el menú de NetApp Backup and Recovery , seleccione *Restaurar*.
. En la lista desplegable a la derecha del campo de búsqueda de nombre, seleccione *Hyper-V*.
. Ingrese el nombre del recurso que desea restaurar o filtre por el nombre de la máquina virtual, el host de la máquina virtual o el grupo de almacenamiento donde se encuentra el recurso que desea restaurar.
+
Aparecerá una lista de instantáneas que coinciden con sus criterios de búsqueda.

. Seleccione el botón *Restaurar* para la instantánea que desea restaurar.
+
Aparece una lista de posibles puntos de restauración.

. Seleccione el punto de restauración que desea utilizar.
. Seleccione una ubicación de origen de la instantánea.
. Seleccione *Siguiente* para continuar.
. Elija el destino de restauración y la configuración:


[discrete]
===== Selección de destino

[role="tabbed-block"]
====
.Restaurar a la ubicación original
--
Al restaurar a la ubicación original, podrá ver las configuraciones de destino expandiendo la sección *Configuraciones de destino*, pero no podrá cambiarlas.

. En la sección *Opciones posteriores a la restauración*, considere la siguiente opción:
+
** *Iniciar la máquina virtual*: habilite esta opción para iniciar la nueva máquina virtual después de restaurarla.


. Seleccione *Restaurar*.


--
.Restaurar a una ubicación alternativa
--
. En la sección *Configuración de destino*, ingrese la siguiente información:
+
** *FQDN o dirección IP de Hyper-V*: ingrese el nombre de dominio completo o la dirección IP del host Hyper-V de destino.
** *Red*: Seleccione la red de destino donde desea restaurar la instantánea.
** *Nombre de la máquina virtual*: Ingrese el nombre de la máquina virtual que desea restaurar.
** *Ubicación de destino*: ingrese la carpeta de destino o el recurso compartido CIFS que debe contener los datos restaurados.


. En la sección *Opciones previas a la restauración*, considere las siguientes opciones:
+
** *Restauración rápida*: habilite esta opción para que la máquina virtual restaurada esté disponible de inmediato. Solo se restauran desde el almacén de objetos los archivos necesarios para ejecutar la máquina virtual, en lugar del volumen completo.


. En la sección *Opciones posteriores a la restauración*, considere las siguientes opciones:
+
** *Iniciar la máquina virtual*: habilite esta opción para iniciar la nueva máquina virtual después de restaurarla.


. Seleccione *Restaurar*.


--
====