---
sidebar: sidebar 
permalink: br-use-dashboard.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, backup, recovery, dashboard, view, health, status, alerts, notifications 
summary: Monitorear el estado de sus cargas de trabajo le garantiza estar al tanto de los problemas con la protección de las cargas de trabajo y poder tomar medidas para resolverlos.  Vea el estado de sus copias de seguridad y restauraciones y responda a cualquier alerta que aparezca en el Panel de control de NetApp Backup and Recovery .  Puede revisar el resumen de protección, el resumen de restauración, el resumen del sistema y más. 
---
= Ver el estado de la protección en el panel de control de Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Supervisa el estado de tus cargas de trabajo para identificar problemas de protección y responder a las alertas. Consulta el estado de los backups y las restauraciones, y revisa los resúmenes de sistema, protección, trabajos y restauración en el panel de control de NetApp Backup and Recovery.

*Rol requerido de NetApp Console*: Backup and Recovery super admin, Backup and Recovery backup admin, Backup and Recovery restore admin, Backup and Recovery clone admin o rol de Backup and Recovery backup viewer. Si estás protegiendo datos almacenados en un clúster de Cloud Volumes ONTAP, también se requiere el rol de Cloud Volumes ONTAP Admin. Más información sobre link:reference-roles.html["Funciones y privilegios de backup y recuperación"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].

.Pasos
. En el menú de la NetApp Console, selecciona *Protección* > *Backup and Recovery*.
. Seleccione un mosaico de carga de trabajo (por ejemplo, Microsoft SQL Server).
. Desde el menú Copia de seguridad y recuperación, seleccione *Panel de control*.
+
Puede revisar los siguientes tipos de información:

+
** Número de hosts o máquinas virtuales descubiertos
** Número de clústeres de Kubernetes descubiertos
** Número de destinos de respaldo en el almacenamiento de objetos
** Número de vCenters
** Número de clústeres de almacenamiento en ONTAP






[[view-the-protection-summary]]
== Ver el resumen de protección

Revise la siguiente información en el Resumen de protección:

* El número total de bases de datos, máquinas virtuales y almacenes de datos protegidos y no protegidos.
+

TIP: Una base de datos protegida es aquella que tiene una política de respaldo asignada.  Una base de datos desprotegida es aquella que no tiene una política de respaldo asignada.

* La cantidad de copias de seguridad que se realizaron correctamente, tuvieron una advertencia o fallaron.
* La capacidad total descubierta por el servicio de respaldo y la capacidad que está protegida versus la que no está protegida.  Pase el cursor sobre el ícono "*i*" para ver los detalles.




[[view-the-job-summary]]
== Ver el resumen del trabajo

Consulta el número total de trabajos completados, en ejecución o fallidos en el resumen de trabajos.

.Pasos
. Para cada distribución de tareas, cambia el filtro para mostrar el resumen de las tareas fallidas, en ejecución y completadas según el número de días, por ejemplo, los últimos 30 días, los últimos 7 días, las últimas 24 horas o el último año.
. Consulta los detalles de los trabajos fallidos, en ejecución y finalizados seleccionando *Ver seguimiento de trabajos*.




[[view-the-restore-summary]]
== Ver el resumen de restauración

Revisa la siguiente información en el resumen de la restauración:

* El número total de trabajos de restauración realizados
* La cantidad total de capacidad que se ha restaurado
* La cantidad de trabajos de restauración realizados en el almacenamiento local, secundario y de objetos.  Pase el cursor sobre el gráfico para ver los detalles.

