---
sidebar: sidebar 
permalink: br-use-manage-execution-hook-templates.html 
keywords: hooks, execution hooks, exec hooks, hook, execution, script, postscript, prescript, post, pre, run, backup, snapshot, freeze 
summary: NetApp Backup and Recovery le permite administrar ganchos de ejecución para tomar medidas antes o después de las operaciones de protección de aplicaciones. 
---
= Gestiona las plantillas de hooks de ejecución de Kubernetes en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Crea plantillas de hooks de ejecución para ejecutar scripts personalizados antes o después de las operaciones de protección de las aplicaciones de Kubernetes gestionadas.

[NOTE]
====
NetApp Backup and Recovery congela y descongela sistemas de archivos para aplicaciones como KubeVirt durante la protección de datos. Puedes desactivar este comportamiento globalmente o para aplicaciones específicas usando la documentación de Trident Protect:

* Para deshabilitar este comportamiento para todas las aplicaciones, consulte https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html#protecting-data-with-kubevirt-vms["Protección de datos con máquinas virtuales KubeVirt"] .
* Para deshabilitar este comportamiento para una aplicación específica, consulte https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-manage-applications.html#define-an-application["Definir una aplicación"] .


====
*Rol de NetApp Console requerido*

Backup and Recovery super admin, Backup and Recovery backup admin o Backup and Recovery restore admin. link:reference-roles.html["Obtenga información sobre los roles de acceso de NetApp Backup and Recovery"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].



[[types-of-execution-hooks]]
== Tipos de ganchos de ejecución

NetApp Backup and Recovery admite los siguientes tipos de ganchos de ejecución según cuándo se ejecutan:

* Pre-instantánea
* Post-instantánea
* Copia de seguridad previa
* Post-copia de seguridad
* Post-restauración




[[order-of-execution]]
=== Orden de ejecución

Cuando se ejecuta una operación de protección de datos, los eventos de gancho de ejecución ocurren en el siguiente orden:

. Todos los ganchos de ejecución de preoperación personalizados aplicables se ejecutan en los contenedores apropiados. Puede crear varios ganchos de preoperación personalizados, pero su orden de ejecución no está garantizado ni es configurable.
. Si corresponde, se producen bloqueos del sistema de archivos.
. Se realiza la operación de protección de datos.
. Los sistemas de archivos congelados se descongelan, si corresponde.
. NetApp Backup and Recovery ejecuta cualquier gancho de ejecución personalizado posterior a la operación que corresponda en los contenedores adecuados. Puedes crear varios ganchos de ejecución personalizados posteriores a la operación, pero su orden de ejecución no está garantizado ni es configurable.


Si creas varios hooks del mismo tipo, no se garantiza su orden de ejecución. Los hooks de diferentes tipos siempre se ejecutan en el orden especificado. Por ejemplo, los hooks se ejecutan en este orden cuando una configuración incluye todos los tipos de hooks compatibles:

. Se ejecutan los hooks previos a la instantánea
. Se ejecutan los hooks posteriores a la instantánea
. Se ejecutan los hooks previos al backup
. Se ejecutan los hooks posteriores a la copia de seguridad



NOTE: Pruebe los scripts de ejecución de gancho antes de habilitarlos en producción.  Utilice 'kubectl exec' para probar scripts, luego verifique las instantáneas y las copias de seguridad clonando la aplicación en un espacio de nombres temporal y restaurándola.


NOTE: Si un gancho de ejecución previo a la instantánea agrega, cambia o elimina recursos de Kubernetes, esos cambios se incluyen en la instantánea o la copia de seguridad y en cualquier operación de restauración posterior.



[[important-notes-about-custom-execution-hooks]]
== Notas importantes sobre los ganchos de ejecución personalizados

Ten en cuenta lo siguiente a la hora de planificar los hooks de ejecución para tus aplicaciones.

* Un gancho de ejecución debe utilizar un script para realizar acciones.  Muchos ganchos de ejecución pueden hacer referencia al mismo script.
* Los «hooks» de ejecución deben ser scripts de shell ejecutables.
* El tamaño del script está limitado a 96 KB.
* Las configuraciones de gancho de ejecución y cualquier criterio coincidente se utilizan para determinar qué ganchos son aplicables a una operación de instantánea, copia de seguridad o restauración.



NOTE: Los ganchos de ejecución pueden reducir o desactivar la funcionalidad de la aplicación. Haz que tus ganchos personalizados se ejecuten lo más rápido posible. Si cancelas una operación de copia de seguridad o de instantánea que tenga ganchos de ejecución asociados, esos ganchos igual se ejecutan si la operación ya comenzó. La lógica de un gancho de ejecución posterior a la copia de seguridad no puede asumir que la copia de seguridad se completó.



[[execution-hook-filters]]
== Filtros de gancho de ejecución

Al añadir o editar un gancho de ejecución para una aplicación, puedes añadir filtros al gancho de ejecución para controlar con qué contenedores coincide dicho gancho. Los filtros son útiles para aplicaciones que usan la misma imagen de contenedor en todos los contenedores, pero pueden usar cada imagen para un propósito diferente (como Elasticsearch). Los filtros te permiten crear escenarios en los que los ganchos de ejecución se ejecutan en algunos, pero no necesariamente en todos los contenedores idénticos. Si creas varios filtros para un solo gancho de ejecución, se combinan con un operador lógico AND. Puedes tener hasta 10 filtros activos por gancho de ejecución.

Cada filtro que añadas a un gancho de ejecución utiliza una expresión regular para identificar contenedores en tu clúster. Cuando un gancho identifica un contenedor, ejecuta el script asociado en dicho contenedor. Las expresiones regulares para los filtros utilizan la sintaxis de Regular Expression 2 (RE2), que no admite la creación de filtros que excluyan contenedores de la lista de coincidencias. Para obtener información sobre la sintaxis que NetApp Backup and Recovery admite para las expresiones regulares en los filtros de los ganchos de ejecución, consulta https://github.com/google/re2/wiki/Syntax["Compatibilidad con la sintaxis de expresiones regulares 2 (RE2)"^].


NOTE: Si agrega un filtro de espacio de nombres a un gancho de ejecución que se ejecuta después de una operación de restauración o clonación y el origen y el destino de la restauración o clonación están en espacios de nombres diferentes, el filtro de espacio de nombres solo se aplica al espacio de nombres de destino.



[[execution-hook-examples]]
== Ejemplos de ganchos de ejecución

Visita el https://github.com/NetApp/Verda["Proyecto NetApp Verda en GitHub"] para descargar ganchos de ejecución reales para aplicaciones populares como Apache Cassandra y Elasticsearch.  También puede ver ejemplos y obtener ideas para estructurar sus propios ganchos de ejecución personalizados.


NOTE: Los scripts en el repositorio Verda GitHub se proporcionan tal cual y no cuentan con soporte oficial por parte de NetApp. Solo el framework de hooks de ejecución dentro de Trident Protect y Backup and Recovery cuenta con soporte oficial por parte de NetApp.



[[create-an-execution-hook-template]]
== Crear una plantilla de gancho de ejecución

Puede crear una plantilla de gancho de ejecución personalizada que pueda utilizar para realizar acciones antes o después de una operación de protección de datos en una aplicación.


NOTE: Las plantillas que crees aquí solo se pueden usar cuando proteges cargas de trabajo de Kubernetes.

.Pasos
. En la consola, vaya a *Protección* > *Copia de seguridad y recuperación*.
. Seleccione la pestaña *Configuración*.
. Expande la sección *Plantilla de gancho de ejecución*.
. Seleccione *Crear plantilla de gancho de ejecución*.
. Introduzca un nombre para el gancho de ejecución.
. Opcionalmente, elija un tipo de enlace. Por ejemplo, un enlace posterior a la restauración se ejecuta una vez finalizada la operación.
. En el cuadro de texto *Script*, ingrese el script de shell ejecutable que desea ejecutar como parte de la plantilla de gancho de ejecución.  Opcionalmente, puede seleccionar *Cargar script* para cargar un archivo de script en su lugar.
. Seleccione *Crear*.
+
Después de crear la plantilla, ésta aparece en la lista de plantillas en la sección *Plantilla de gancho de ejecución*.


