---
sidebar: sidebar 
permalink: br-use-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Protege tus cargas de trabajo VMware con NetApp Backup and Recovery. 
---
= Protege las cargas de trabajo de VMware con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utiliza NetApp Backup and Recovery para proteger las máquinas virtuales (VM) y los datastores de VMware. Puedes crear backups rápidos, con gestión eficiente del espacio, consistentes ante fallos y consistentes con las máquinas virtuales, almacenarlos en destinos de backup compatibles y restaurar cargas de trabajo de VMware en un host de VMware local.


NOTE: Esta versión de NetApp Backup and Recovery solo es compatible con VMware vCenter y no detecta vVols ni máquinas virtuales en vVols.

Utiliza NetApp Backup and Recovery para implementar una estrategia 3-2-1 con 3 copias de tus datos de origen en 2 sistemas de almacenamiento diferentes y 1 copia en la nube. Las ventajas del enfoque 3-2-1 incluyen:

* Múltiples copias de datos protegen contra amenazas cibernéticas internas y externas.
* El uso de diferentes tipos de medios le ayudará a recuperarse si uno de ellos falla.
* Puedes restaurar rápidamente a partir de la copia local y utilizar las copias externas si la copia local se ve comprometida.


Puede utilizar NetApp Backup and Recovery para realizar las siguientes tareas relacionadas con las cargas de trabajo de VMware:

* link:br-use-vmware-discovery.html["Descubra las cargas de trabajo de VMware"]
* link:br-use-vmware-protection-groups.html["Crear y administrar grupos de protección para cargas de trabajo de VMware"]
* link:br-use-vmware-backup.html["Realizar copias de seguridad de las cargas de trabajo de VMware"]
* link:br-use-vmware-restore.html["Restaurar cargas de trabajo de VMware"]

