---
sidebar: sidebar 
permalink: br-use-back-up-now-kubernetes-applications-web-ui.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: Crea manualmente copias de seguridad bajo demanda de aplicaciones de Kubernetes usando la interfaz web de NetApp Backup and Recovery. 
---
= Haz una copia de seguridad de una aplicación de Kubernetes usando la interfaz web de NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utiliza la interfaz de usuario web para realizar una copia de seguridad bajo demanda de una aplicación de Kubernetes.

*Rol de NetApp Console requerido*

Superadministrador de NetApp Backup and Recovery o administrador de backup de NetApp Backup and Recovery. link:reference-roles.html["Obtenga información sobre los roles de acceso de NetApp Backup and Recovery"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].



[[back-up-a-kubernetes-application]]
== Realiza una copia de seguridad de una aplicación de Kubernetes

Cree manualmente una copia de seguridad de una aplicación de Kubernetes para establecer una línea de base para futuras copias de seguridad e instantáneas, o para garantizar que los datos más recientes estén protegidos.

.Pasos
. En NetApp Backup and Recovery, seleccione *Inventario*.
. Elige una instancia de Kubernetes y selecciona *Ver* para acceder a los recursos asociados a dicha instancia.
. Seleccione la pestaña *Aplicaciones*.
. En la lista de aplicaciones, selecciona una aplicación de la que quieras hacer backup y elige el menú Acciones correspondiente.
. Seleccione *Hacer copia de seguridad ahora*.
. Comprueba que la aplicación seleccionada sea la correcta.
. Seleccione *Hacer copia de seguridad*.


.Resultado
La consola crea una copia de seguridad de la aplicación y muestra el progreso en el área *Monitoreo* de Copia de seguridad y recuperación. La copia de seguridad se crea según la política de protección asociada a la aplicación.
