---
sidebar: sidebar 
permalink: br-use-manage-kubernetes-clusters.html 
keywords: discover, backup and recovery, snapcenter, kubernetes, k8s, clusters, applications, inventory 
summary: NetApp Backup and Recovery le permite descubrir y administrar sus clústeres de Kubernetes para que pueda proteger los recursos alojados en los clústeres. 
---
= Administrar clústeres de Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery le permite descubrir y administrar sus clústeres de Kubernetes para que pueda proteger los recursos alojados en los clústeres.

.Rol de NetApp Console requerido
Administrador de la organización o administrador de SnapCenter . link:reference-roles.html["Obtenga información sobre los roles de acceso de NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^] .


NOTE: Para descubrir clústeres de Kubernetes, consultelink:br-start-discover.html["Descubra las cargas de trabajo de Kubernetes"] .



== Editar la información del clúster de Kubernetes

Puede editar un clúster si necesita cambiar su nombre.

.Pasos
. En NetApp Backup and Recovery, seleccione *Inventario* > *Clústeres*.
. En la lista de clústeres, elija el clúster que desee editar y seleccione el menú Acciones asociado.
. Seleccione *Editar clúster*.
. Realice los cambios necesarios en el nombre del clúster. El nombre del clúster debe coincidir con el que utilizó con el comando Helm durante el proceso de descubrimiento.
. Seleccione *Listo*.




== Eliminar un clúster de Kubernetes

Para dejar de proteger un clúster de Kubernetes, deshabilite la protección y elimine las aplicaciones asociadas; luego, elimine el clúster de NetApp Backup and Recovery.  NetApp Backup and Recovery no elimina el clúster ni sus recursos; solo elimina el clúster del inventario de la NetApp Console .

.Pasos
. En NetApp Backup and Recovery, seleccione *Inventario* > *Clústeres*.
. En la lista de clústeres, elija el clúster que desee editar y seleccione el menú Acciones asociado.
. Seleccione *Eliminar clúster*.
. Revise la información en el cuadro de diálogo de confirmación y seleccione *Eliminar*.

