---
sidebar: sidebar 
permalink: br-use-reports.html 
keywords: backing up, back up, backup, backup on-prem ontap, policy, policies, backup policies, cloud backup, aws, aws s3, azure, google cloud 
summary: En NetApp Backup and Recovery, cree informes para ver el estado de sus copias de seguridad, incluida la cantidad de copias de seguridad realizadas, la cantidad de copias de seguridad realizadas correctamente y la cantidad de copias de seguridad fallidas.  También puede ver los detalles de cada copia de seguridad, incluido el tipo de copia de seguridad, el sistema de almacenamiento utilizado para la copia de seguridad y la hora de la copia de seguridad. 
---
= Cree informes para cargas de trabajo de Microsoft SQL Server en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
En NetApp Backup and Recovery, cree informes para las cargas de trabajo de Microsoft SQL Server para ver el estado de sus copias de seguridad, incluida la cantidad de copias de seguridad, la cantidad de copias de seguridad exitosas y la cantidad de copias de seguridad fallidas.  También puede ver los detalles de cada copia de seguridad, incluido el tipo de copia de seguridad, el sistema de almacenamiento utilizado para la copia de seguridad y la hora de la copia de seguridad.



== Crear un informe

*Rol de NetApp Console requerido* Visor de almacenamiento, Superadministrador de Backup and Recovery, Administrador de backup de Backup and Recovery, Administrador de restauración de Backup and Recovery, Administrador de clones de Backup and Recovery.  Conozca más sobrelink:reference-roles.html["Roles y privilegios de copia de seguridad y recuperación"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^] .

. En el menú NetApp Backup and Recovery , seleccione la opción *Informes*.
. Seleccione *Crear informe*.
. Introduzca los detalles del alcance del informe:
+
** *Nombre del informe*: Ingrese un nombre único para el informe.
** *Tipo de informe*: elija si desea un informe por cuenta o por carga de trabajo (Microsoft SQL Server).
** *Seleccionar host*: si seleccionó por carga de trabajo, seleccione el host para el cual desea generar el informe.
** *Seleccionar contenidos*: elija si desea que el informe incluya un resumen de todas las copias de seguridad o detalles de cada copia de seguridad.  (Si eligió "Por cuenta")


. Ingresar rango de informe: elija si desea que el informe incluya datos del último día, los últimos 7 días, los últimos 30 días, el último trimestre o el año pasado.
. Ingrese los detalles de entrega del informe: si desea que el informe se envíe por correo electrónico, marque *Enviar informe mediante correo electrónico*.  Introduzca las direcciones de correo electrónico donde desea que se envíe el informe.
+
Configure las notificaciones por correo electrónico en la página Configuración.  Para obtener detalles sobre cómo configurar las notificaciones por correo electrónico, consultelink:br-use-settings-advanced.html["Configurar ajustes"] .


