---
sidebar: sidebar 
permalink: br-use-vmware-guest-file-restore-scenarios-you-might-encounter.html 
keywords:  
summary: Al intentar restaurar un archivo invitado, es posible que se encuentre con situaciones en las que la sesión de restauración del archivo invitado esté en blanco, la operación de conexión de disco para la restauración del archivo invitado falle o las copias de seguridad no se desconecten después de que se interrumpa la sesión de restauración del archivo invitado. 
---
= Soluciona problemas de restauración de archivos invitados de VMware en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si tienes problemas al restaurar un archivo de invitado, utiliza estos escenarios para identificar y corregir el problema.



[[guest-file-restore-session-is-blank]]
== La sesión de restauración de archivos de invitado está en blanco

Este problema ocurre si crea una sesión de restauración de archivos invitados y el sistema operativo invitado se reinicia durante la sesión. Los VMDK en el sistema operativo invitado pueden permanecer fuera de línea, por lo que la lista de sesiones de restauración de archivos del invitado estará en blanco.

Para corregir el problema, vuelva a poner manualmente los VMDK en línea en el sistema operativo invitado. Cuando los VMDK estén en línea, la sesión de restauración de archivos invitados mostrará el contenido correcto.



[[guest-file-restore-attach-disk-operation-fails]]
== La operación de adjuntar disco para restaurar el archivo invitado falla

Este problema se produce cuando inicias una operación de restauración de archivos del sistema invitado, pero la operación de conexión del disco falla aunque VMware Tools se está ejecutando y las credenciales del sistema operativo invitado son correctas. Si esto ocurre, se muestra el siguiente error:

`Error while validating guest credentials, failed to access guest system using specified credentials: Verify VMware Tools is running properly on the system and that the account used is an Administrator account. Error is SystemError vix error codes = (3016, 0).`

Para solucionar el problema, reinicia el servicio de VMware Tools de Windows en el sistema operativo invitado y luego vuelve a intentar la operación de restauración de archivos del sistema invitado.



[[backups-are-not-detached-after-guest-file-restore-session-is-discontinued]]
== Las copias de seguridad no se separan después de que se interrumpe la sesión de restauración de archivos del invitado

Este problema ocurre cuando se realiza una operación de restauración de archivo invitado desde una copia de seguridad consistente con la máquina virtual. Mientras la sesión de restauración de archivos invitados está activa, se realiza otra copia de seguridad consistente con la misma máquina virtual para la misma máquina virtual. Cuando la sesión de restauración de archivos invitados se desconecta, ya sea de forma manual o automática después de 24 horas, las copias de seguridad de la sesión no se separan.

Para corregir el problema, desconecte manualmente los VMDK que se adjuntaron de la sesión de restauración de archivos del invitado activo.
