---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: Comience a utilizar NetApp Backup and Recovery verificando la preparación de su entorno operativo, el agente de consola y la cuenta de consola.  Para utilizar NetApp Backup and Recovery, necesitará estos requisitos previos. 
---
= NetApp requisitos de copia de seguridad y recuperación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de empezar a utilizar NetApp Backup and Recovery, asegúrate de que tu NetApp Console y tu entorno operativo cumplen los siguientes requisitos.



== Prepara la consola NetApp

Accedes a NetApp Backup and Recovery a través de NetApp Console. Para preparar la Console para Backup and Recovery, debes:

* Agrega un agente de Consola
* Agrega al menos un sistema de almacenamiento
* Configura una organización de Console y roles de usuario


Necesitas el rol de administrador de la organización o superadministrador en NetApp Console para completar esta preparación.

Para obtener más información sobre NetApp Console, consulta https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console para la gestión unificada del almacenamiento"^].



=== Completa la configuración inicial de la consola NetApp

Completa la configuración inicial de NetApp Console si aún no lo has hecho.

https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Flujo de trabajo inicial para NetApp Console (aplicación SaaS)"^]



=== Despliega un agente de consola

Un agente de Console es un componente de software ligero que instalas en tu red para conectar tu infraestructura de almacenamiento a NetApp Console. Permite la orquestación avanzada del almacenamiento, los servicios de datos y la integración segura en la nube.

https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Obtenga más información sobre los agentes de consola"^] https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html["Despliega un agente de consola"^]



=== Agrega un sistema de almacenamiento

Antes de poder proteger las cargas de trabajo en Backup and Recovery, necesitas añadir un sistema de almacenamiento ONTAP a la NetApp Console.

https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Descubre los clústeres ONTAP locales en NetApp Console"^]



=== Configura una organización y los roles de usuario

Conoce las organizaciones, los proyectos y los roles de usuario, y luego configura a los usuarios con los permisos adecuados que necesitan para realizar sus tareas.

Consulta https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html["Añade usuarios a una organización de NetApp Console"] para obtener información sobre el uso de una organización y proyectos para controlar el acceso a los recursos.

Consulta https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["Funciones de NetApp Backup and Recovery en la NetApp Console"] para obtener información detallada sobre las funciones y los permisos necesarios para realizar operaciones en NetApp Backup and Recovery.



== Requisitos de las copias de seguridad en el almacenamiento de objetos

Para utilizar el almacenamiento de objetos como destinos de backup, necesitas una cuenta con AWS S3, Google Cloud Storage, Microsoft Azure Blob, StorageGRID u ONTAP y los permisos de acceso adecuados configurados.



== Requisitos para proteger las cargas de trabajo de volumen de ONTAP

Para utilizar NetApp Backup and Recovery para cargas de trabajo de volumen ONTAP, necesitas los siguientes requisitos previos de sistema host, espacio y ajuste de tamaño.

* Se requiere ONTAP 9.8 o posterior.
* Se requiere ONTAP 9.12.1 o una versión posterior para la protección de volúmenes FlexGroup. Consulta link:br-reference-limitations.html["Limitaciones conocidas con NetApp Backup and Recovery para volúmenes ONTAP"] para más información.
* Se requiere ONTAP 9.17.1 o una versión posterior para hacer copias de seguridad o restaurar en un almacenamiento de objetos compatible con S3.
* Se debe activar una licencia de ONTAP One en la instancia local de ONTAP.


Para obtener información sobre las funciones compatibles, los tipos de volumen, los destinos de copia de seguridad y restauración, y más, consulta link:prev-ontap-protect-overview.html["Proteja sus datos de volumen de ONTAP"].



== Requisitos para proteger las cargas de trabajo de Microsoft SQL Server

Para utilizar NetApp Backup and Recovery para cargas de trabajo de Microsoft SQL Server, necesita los siguientes requisitos previos de tamaño, espacio y sistema host.

[cols="33,66a"]
|===
| Artículo | Requisitos 


| Sistemas operativos  a| 
Microsoft Windows Para obtener la información más reciente sobre las versiones compatibles, consulte https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Herramienta de matriz de interoperabilidad de NetApp"^] .



| Versiones de Microsoft SQL Server  a| 
Las versiones 2012 y posteriores son compatibles con VMware Virtual Machine File System (VMFS) y VMware Virtual Machine Disk (VMDK) NFS.



| Versión del servidor SnapCenter  a| 
Se requiere la versión 5.0 o superior de SnapCenter Server si va a importar sus datos existentes de SnapCenter a NetApp Backup and Recovery.


NOTE: Si ya tiene SnapCenter, primero verifique que cumple con los requisitos previos antes de importar desde SnapCenter.  Verlink:concept-start-prereq-snapcenter-import.html["Requisitos previos para importar recursos desde SnapCenter"] .



| RAM mínima para el complemento en el host de SQL Server  a| 
1 GB



| Espacio mínimo de instalación y registro para el complemento en el host de SQL Server  a| 
5 GB

Asigne suficiente espacio en disco y supervise el consumo de almacenamiento de la carpeta de registros.  El espacio de registro necesario varía según la cantidad de copias de seguridad realizadas y la frecuencia de las operaciones de protección de datos.  Si no hay suficiente espacio, no se crearán los registros para las operaciones.



| Paquetes de software necesarios  a| 
* ASP.NET Core Runtime 8.0.24 Hosting Bundle (y todos los parches posteriores de 8.0.x)
* PowerShell 7.4.13


Para obtener la información más reciente sobre las versiones compatibles, consulte la https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Herramienta de matriz de interoperabilidad de NetApp"^] .

|===
[cols="33,66a"]
|===
| Host de base de datos | Almacenamiento compatible 


| Servidor físico  a| 
* LUNs presentadas por Fibre Channel
* LUNs presentadas a través de iSCSI




| Máquina virtual de VMware  a| 
* LUNs iSCSI conectados directamente al sistema invitado por el iniciador iSCSI
* Sistemas de archivos de máquinas virtuales (VMFS)
* Almacenes de datos NFS




| Máquina virtual Hyper-V  a| 
LUNs iSCSI conectados directamente al sistema invitado por el iniciador iSCSI


NOTE: No se admite la protección de bases de datos almacenadas en discos pass-through o archivos VHD/VHDX que se aprovisionan en el almacenamiento NetApp.

|===


== Requisitos para proteger las cargas de trabajo de VMware

Necesita requisitos específicos para descubrir y proteger sus cargas de trabajo de VMware.

|===
| Requisito | Compatible 


| Tipos de almacenes de datos | NFSv3, NFSv4.1 y VMFS 


| Versiones de VMware ESXi Server | 7.0U1 y superiores 


| VMware vCenter vSphere versiones | 7.0U1 y superiores 


| VMware Tools | VMWare Tools es necesario cuando se utiliza la función de restauración de archivos y carpetas y las copias de seguridad coherentes con VM. Para asegurarte de que la versión de VMware Tools coincide con tu versión de ESXi Server, consulta la  https://packages.vmware.com/tools/versions["Información de asignación de versiones de VMware"]. 


| Tipos de dirección IP | IPv4, IPv6 


| Versiones TLS de VMware | 1.2, 1.3 


| Almacenamiento conectado  a| 
* ONTAP 9.13.1 o posterior
* Amazon FSx para sistemas de almacenamiento NetApp ONTAP que ejecuten la versión 9.13.1 o posterior
* Sistemas ASA r2 solo SAN (se requiere ONTAP 9.17.1 o posterior)


|===
[cols="33,66a"]
|===
| Tipo de puerto | Puerto preconfigurado 


| Puerto del servidor VMware ESXi  a| 
443 (HTTPS), bidireccional. La función de restauración de archivos y carpetas utiliza este puerto.



| Clúster de almacenamiento o puerto de máquina virtual de almacenamiento  a| 
* 443 (HTTPS), bidireccional.
* 80 (HTTP), bidireccional. Este puerto se usa para la comunicación entre el dispositivo virtual y la storage VM o el cluster que contiene la storage VM.


|===
.Requisitos de control de acceso basado en roles (RBAC) para proteger las cargas de trabajo de VMware
Tu cuenta de usuario de NetApp Console necesita tener el rol de superadministrador de NetApp Backup and Recovery para trabajar con cargas de trabajo de VMware.

Para obtener más información sobre las funciones de copia de seguridad y recuperación, consulta https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["Funciones de copia de seguridad y recuperación en NetApp Console"].



== Requisitos para proteger las cargas de trabajo de KVM

Necesita requisitos específicos para descubrir y proteger máquinas virtuales KVM.

* Una distribución de Linux moderna que ejecuta la versión del kernel 5.14.0-503.22.1.el9_5.x86_64 (a largo plazo) o posterior
* Sus hosts KVM y máquinas virtuales deben estar administrados por una plataforma de administración. NetApp Backup and Recovery admite las siguientes plataformas de administración:
+
** Apache CloudStack 4.22.0.0


* Asegúrese de que el tráfico de red entrante al puerto 22 esté permitido desde el agente de la consola al host KVM
* Agente invitado QEMU versión 9.0.0 o posterior
* libvirt versión 10.5.0 o posterior



NOTE: Para garantizar que las restauraciones de la carga de trabajo de KVM se completen correctamente, asegúrese de que la configuración *Habilitar instantánea consistente con VM* esté activa en la política de protección que utiliza para las copias de seguridad de KVM.

[NOTE]
====
Para habilitar la protección de las máquinas virtuales KVM administradas por usuarios sin privilegios de administrador, siga los siguientes pasos:

. Monta el volumen como tipo NFS3 para evitar el uso de `nobody` usuario y grupo.
. Utilice el siguiente comando para agregar un usuario sin privilegios de administrador al `qemu` grupo preservando sus grupos existentes:
+
[source, console]
----
usermod -aG qemu <non-root-user>
----
. Utilice el siguiente comando para otorgar la propiedad de la ruta de montaje al `qemu` Usuario y grupo, y cambiar permisos para la ruta de montaje:
+
[source, console]
----
chown -R qemu:qemu <kvm_vm_mount_path> & chmod 771 <kvm_vm_mount_path>
----
. Elimine el directorio NetApp_SnapCenter_Backups existente, si lo hubiera.


====


== Requisitos para proteger las cargas de trabajo de Oracle Database

Asegúrate de que tu entorno cumple los requisitos específicos para descubrir y proteger los recursos de Oracle Database.

|===
| Requisito | Compatible 


| Topología de despliegue  a| 
* Autónomo (NFS, SAN, ASM SAN)
* RAC sobre ASM (VMDK en VMFS)




| Versiones de Oracle Database  a| 
* Oracle Database 19c
* Oracle Database 21c
* Oracle AI Database 26ai




| Almacenamiento de bases de datos | Debe desplegarse en NetApp ONTAP (primario o secundario) 


| OS del host  a| 
* Red Hat Enterprise Linux 8
* Red Hat Enterprise Linux 9




| Almacenamiento de objetos (destinos de backup)  a| 
* Almacenamiento de objetos de Azure
* Amazon AWS
* StorageGRID en NetApp
* ONTAP S3


|===


== Requisitos para proteger las aplicaciones de Kubernetes

Necesita requisitos específicos para descubrir recursos de Kubernetes y proteger sus aplicaciones de Kubernetes.

Para conocer los requisitos de NetApp Console, consulta <<Prepara la consola NetApp>>.


NOTE: NetApp recomienda encarecidamente asignar una dirección IP estática al agente de Console que uses para las cargas de trabajo de Kubernetes para evitar problemas si cambia la dirección IP del agente.

* Un sistema ONTAP primario (los sistemas ASA r2 no son compatibles)
* NetApp Trident 25.02 o posterior
* NetApp Trident Protect 26.05 o posterior (instalado en el clúster Kubernetes durante el descubrimiento)
* Un clúster Kubernetes: las distribuciones y versiones de Kubernetes compatibles incluyen las compatibles con https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["Trident Protect"].
+
** Asegúrate de que el puerto TCP 443 no esté filtrado en la dirección de salida entre el clúster de Kubernetes, el Trident Protect Connector y el Trident Protect proxy.






== Requisitos para proteger las cargas de trabajo de Hyper-V

Asegúrese de que su instancia de Hyper-V cumpla con los requisitos específicos para descubrir y proteger máquinas virtuales.

|===
| Requisito | Compatible 


| Microsoft Hyper-V | 2019, 2022 y 2025 ediciones 


| ASP.NET Core Runtime | 8.0.24 Hosting Bundle (y todos los parches posteriores de 8.0.x) 


| PowerShell | 7.4.13 o posterior 


| Si usuarios que no son administradores van a proteger máquinas virtuales Hyper-V, asegúrate de que los usuarios tienen los siguientes permisos  a| 
* Miembro del grupo de administradores locales
* Parte de la política de seguridad local "Log on as service"




| Asegúrate de que el tráfico HTTPS bidireccional esté permitido para los siguientes puertos en la configuración del Firewall de Windows  a| 
* TCP 8144 (plugin de NetApp para Hyper-V)
* TCP 8145 (Plugin de NetApp para Windows)




| Almacenamiento conectado  a| 
* ONTAP 9.13.1 o posterior
* Comparticiones SMB
* Almacenamiento SAN conectado a través de iSCSI o Fibre Channel


|===
.Requisitos de hardware para el host Hyper-V
* Se admiten hosts independientes y agrupados en FCI
* 1 GB de RAM como mínimo para el complemento Hyper-V de NetApp en el host Hyper-V
* 5 GB de espacio mínimo de instalación y registro para el complemento en el host Hyper-V
+

NOTE: Asegúrese de asignar suficiente espacio en disco en el host Hyper-V para la carpeta de registros y monitoree periódicamente su uso.  El espacio requerido depende de la frecuencia con la que se realizan copias de seguridad y operaciones de protección de datos.  Si no hay suficiente espacio, no se generarán registros.



.NetApp requisitos de configuración de ONTAP
* Un sistema ONTAP primario (ONTAP 9.14.1 o posterior)
* En el caso de las implementaciones de Hyper-V que utilicen recursos compartidos SMB para almacenar datos de máquinas virtuales, asegúrate de que la propiedad de disponibilidad continua del recurso compartido esté habilitada en el sistema ONTAP. Consulta la  https://docs.netapp.com/us-en/ontap/smb-hyper-v-sql/configure-shares-continuous-availability-task.html["Documentación de ONTAP"^] para obtener instrucciones.

