---
sidebar: sidebar 
permalink: enable-preview-features.html 
keywords: preview features, preview, Backup and Recovery, configuration, NetApp Backup and Recovery 
summary: Habilita la vista previa y las funciones ocultas para NetApp Backup and Recovery. 
---
= Activar la vista previa y las funciones ocultas para NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sigue estos pasos para habilitar las funciones en vista previa y ocultas de NetApp Backup and Recovery. Utiliza las funciones en vista previa con precaución en entornos de producción.

*Rol requerido de NetApp Console*: superadministrador de Backup and Recovery. Si estás protegiendo datos almacenados en un clúster de Cloud Volumes ONTAP, también se requiere el rol de Cloud Volumes ONTAP Admin. Conoce más sobre link:reference-roles.html["Roles y privilegios de copia de seguridad y recuperación"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].



[[available-preview-features]]
== Funciones de previsualización disponibles

Puedes activar las siguientes funciones de vista previa para NetApp Backup and Recovery.

[[anchor-flags]]
[cols="50,50"]
|===
| Indicador de funcionalidad | Descripción de la función 


| `"folder-restore-from-local": true` | Habilita la restauración a nivel de carpeta a partir de instantáneas de volúmenes locales de ONTAP. Por defecto, ONTAP solo admite la restauración de carpetas a partir de copias de seguridad de almacenamiento de objetos. Con este indicador habilitado, también puedes restaurar directorios completos a partir de instantáneas locales y replicadas. 


| `"prioritize-restore": true` | Hace que la opción *Priorizar la restauración sobre la cola de trabajos existente* se pueda seleccionar durante el flujo de trabajo de restauración en la interfaz web de NetApp Backup and Recovery. Cuando seleccionas esta opción durante el flujo de trabajo de restauración, las operaciones de restauración tienen prioridad sobre otros trabajos en cola, así que se ejecutan incluso cuando la cola está ocupada. 


| `"data-transfer-report": true` | Activa el informe diario de transferencia de datos de copia de seguridad en la pestaña Informes de NetApp Backup and Recovery for Volumes. El informe proporciona información diaria sobre la actividad de transferencia de datos de copia de seguridad y replicación en todo tu entorno. 


| `"use-azure-msi-cvo": true` | Habilita la opción de usar la autenticación de identidad administrada de Microsoft Entra ID para el almacenamiento de objetos de Azure en lugar de usar una clave de acceso de la cuenta de almacenamiento. Compatible con Cloud Volumes ONTAP en sistemas de Azure que ejecutan ONTAP 9.16.1 o una versión posterior (el agente de la consola también debe residir en Azure). Para obtener más información, consulta link:prev-ontap-backup-cvo-azure.html#anchor-entraid["Requisitos para usar la autenticación de Microsoft Entra ID con los almacenes de objetos de Azure"]. 
|===


[[enable-preview-features]]
== Activar funciones de vista previa

Activa las feature flags de vista previa para usar funcionalidades que aún no están disponibles de forma general. Usa las funciones de vista previa con precaución en entornos de producción.


NOTE: Estos ejemplos suponen que usas Docker; si usas Podman, ejecuta los comandos equivalentes de Podman.

.Pasos
. Utiliza SSH para iniciar sesión en el agente de la Console.
. Cambia al usuario raíz:
+
[source, shell]
----
sudo su
----
. Encuentra el volumen de Backup and Recovery en Docker:
+
[source, shell]
----
docker volume ls | grep cbs
----
+
El resultado debería ser similar al siguiente:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
. Encuentra el punto de montaje del volumen:
+
[source, shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
El punto de montaje difiere entre los despliegues en nube y privados. Este ejemplo de salida muestra un despliegue en nube:

+
[listing]
----
/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Cambia al directorio docker volume config, que está dentro del directorio mountpoint. Por ejemplo:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data/cbs_config
----
. Crea un archivo que contenga la siguiente estructura JSON y un par clave/valor para cada indicador de función que quieras activar. Nombra el archivo según tu tipo de implementación:
+
** Despliegue en la nube: `production-customer.json`
** Despliegue en sitios privados / oscuros: `darksite-customer.json`
+
Consulta <<anchor-flags,banderas disponibles>> para obtener información sobre los indicadores de características. Por ejemplo:

+
[source, json]
----
{
  "feature-flags": {
    "folder-restore-from-local": true,
    "prioritize-restore": true
  }
}
----


. Reinicia el contenedor de NetApp Backup and Recovery:
+
[source, shell]
----
docker restart cloudmanager_cbs
----
. Vuelve a cargar la interfaz de usuario de NetApp Backup and Recovery en tu navegador web.
+

NOTE: Para desactivar una función de vista previa, sigue los mismos pasos pero establece el valor del indicador de función en `false`.





[[disable-indexing-for-volumes]]
== Desactivar la indexación de volúmenes

Desactiva la indexación para volúmenes específicos o para todos los volúmenes que pertenezcan a una o más storage VMs usando las siguientes flags de opción:

* `svms-not-to-index`: una lista separada por comas de las máquinas virtuales de almacenamiento cuyos volúmenes no deben indexarse
* `volumes-not-to-index`: una lista, separada por comas, de los identificadores individuales de los volúmenes que no deben indexarse



NOTE: Estos ejemplos suponen que usas Docker; si usas Podman, ejecuta los comandos equivalentes de Podman.

.Pasos
. Utiliza SSH para iniciar sesión en el agente de la Console.
. Cambia al usuario raíz:
+
[source, shell]
----
sudo su
----
. Encuentra el volumen de Backup and Recovery en Docker:
+
[source, shell]
----
docker volume ls | grep cbs
----
+
El resultado debería ser similar al siguiente:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
. Encuentra el punto de montaje del volumen:
+
[source, shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
El punto de montaje difiere entre los despliegues en nube y privados. Este ejemplo de salida muestra un despliegue en nube:

+
[listing]
----
/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Cambia al directorio docker volume config, que está dentro del directorio mountpoint. Por ejemplo:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data/cbs_catalog_config
----
. Crea un archivo llamado `production-customer.json` y personaliza los nombres de las máquinas virtuales de almacenamiento y los ID de volumen para que coincidan con tu entorno:
+
[source, json]
----
{
  "indexing": {
    "svms-not-to-index": "storage_vm_name_1,storage_vm_name_2,storage_vm_name_3",
    "volumes-not-to-index": "volume_ID_1,volume_ID_2,volume_ID_3"
  }
}
----
. Reinicia el contenedor del catálogo de indexación de NetApp Backup and Recovery:
+
[source, shell]
----
docker restart cloudmanager_cbs_catalog
----

