---
sidebar: sidebar 
permalink: prev-ontap-backup-onprem-s3-compatible.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, S3, compatible, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Protege tus cargas de trabajo VMware con NetApp Backup and Recovery. 
---
= Haz una copia de seguridad de los datos de ONTAP locales en un almacenamiento compatible con S3 con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Completa unos pasos en NetApp Backup and Recovery para empezar a hacer copias de seguridad de los datos de volúmenes de tus sistemas ONTAP locales principales. Puedes enviar las copias de seguridad a un sistema de almacenamiento ONTAP secundario (un volumen replicado), a un bucket en un sistema de almacenamiento compatible con S3 o a ambos.



[[verify-support-for-your-configuration]]
== Verificar la compatibilidad con su configuración

Lee los siguientes requisitos para asegurarte de que tienes una configuración compatible antes de empezar a hacer copias de seguridad de volúmenes en un almacenamiento compatible con S3.

Versiones de ONTAP compatibles:: Se requiere una versión mínima de ONTAP 9.17.1.




[[supported-actions]]
=== Acciones compatibles

A continuación se indican las acciones admitidas al realizar una copia de seguridad en un almacenamiento compatible con S3:

* Copia de seguridad de instantáneas coherentes con fallos y coherentes con aplicaciones desde ONTAP local a almacenes de objetos de terceros compatibles con S3
* Flujos de trabajo básicos para la protección de datos: copia de seguridad, restauración y eliminación de copia de seguridad
* Probado y validado con el almacenamiento de objetos Wasabi; los clientes también han informado de implementaciones satisfactorias con MinIO e IBM Cloud Object Storage
* NetApp Support acepta y clasifica todas las solicitudes de soporte que involucren almacenes de objetos compatibles con S3 de terceros




[[unsupported-features-and-configurations]]
=== Funciones y configuraciones no compatibles

Las siguientes funciones y configuraciones no son compatibles al realizar copias de seguridad en almacenamiento compatible con S3:

* Bring Your Own Bucket (BYOB) no es compatible
* No se admite la habilitación de DataLock en las políticas de backup
* No se admite la activación del modo de archivo en las políticas de backup
* Las opciones de cifrado a nivel de bucket no son compatibles
* MetroCluster no se admiten las configuraciones
* Los entornos ONTAP basados en cloud no son compatibles; solo se admite ONTAP local




[[caveats]]
=== Advertencias

Ten en cuenta los siguientes puntos cuando hagas copias de seguridad en un almacenamiento compatible con S3:

* *El rendimiento no está garantizado*: los productos de NetApp son sensibles a la latencia y las IOPS de la API de S3. Los almacenes de objetos de terceros deben proporcionar una latencia y unas IOPS equivalentes a las de AWS S3 para lograr un rendimiento comparable. NetApp no soluciona problemas de rendimiento del almacén de objetos.
* *Sin responsabilidad por corrupción o pérdida de datos*: NetApp no se hace responsable de la pérdida de datos ni del tiempo de inactividad del servicio causado por problemas con almacenes de objetos S3 de terceros.
* *Soporte de funciones limitado*: El conjunto de características admitidas para los destinos compatibles con S3 de terceros es un subconjunto de lo que está disponible para los destinos nativos (AWS S3, Azure Blob, GCP, ONTAP S3, StorageGRID).




[[prepare-your-console-agent]]
== Prepare su agente de consola

El agente de consola es el software principal para la funcionalidad de la consola.  Se requiere un agente de consola para realizar copias de seguridad y restaurar sus datos de ONTAP .



[[create-or-switch-console-agents]]
=== Crear o cambiar agentes de consola

Cuando haces una copia de seguridad de los datos en un almacenamiento compatible con S3, debe haber un agente de Console disponible en tus instalaciones o en la nube. Tendrás que instalar un nuevo agente de Console o asegurarte de que el agente de Console seleccionado actualmente esté en una de estas ubicaciones. El agente de Console local se puede instalar en un sitio con o sin acceso a internet.

* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["Obtenga más información sobre los agentes de consola"^]
* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#how-to-create-a-connector["Instalar el agente de consola en su entorno de nube"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-connector-on-prem.html["Instalación del agente de consola en un host Linux con acceso a Internet"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-private-mode.html["Instalación del agente de consola en un host Linux sin acceso a Internet"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["Cambiar entre agentes de la consola"^]




[[prepare-console-agent-networking-requirements]]
=== Preparar los requisitos de red del agente de consola

Asegúrese de que la red donde está instalado el agente de consola permita las siguientes conexiones:

* Una conexión HTTPS a través del puerto 443 al servidor compatible con S3
* Una conexión HTTPS a través del puerto 443 a su LIF de administración del clúster ONTAP de origen
* Una conexión a Internet saliente a través del puerto 443 hacia NetApp Backup and Recovery (no es necesaria cuando el agente de la consola está instalado en un sitio "oscuro")




==== Consideraciones sobre el modo privado (sitio oscuro)

La funcionalidad de NetApp Backup and Recovery está integrada en el agente de consola.  Cuando se instala en modo privado, necesitará actualizar periódicamente el software del agente de la consola para obtener acceso a nuevas funciones.  Comprueba ellink:whats-new.html["Novedades de NetApp Backup and Recovery"] para ver las nuevas funciones en cada versión de NetApp Backup and Recovery .  Cuando desee utilizar las nuevas funciones, siga los pasos para https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-connector.html["actualizar el software del agente de la consola"^] .

Cuando usas NetApp Backup and Recovery en un entorno SaaS estándar, los datos de configuración de NetApp Backup and Recovery se respaldan en la nube. Cuando usas NetApp Backup and Recovery en un sitio sin acceso a internet, los datos de configuración de NetApp Backup and Recovery se respaldan en el bucket compatible con S3 donde se están almacenando tus backups.



[[verify-license-requirements]]
== Verificar los requisitos de la licencia

Antes de poder activar NetApp Backup and Recovery para su clúster, deberá comprar y activar una licencia BYOL de NetApp Backup and Recovery de NetApp. La licencia es para realizar copias de seguridad y restaurar en almacenamiento de objetos; no se necesita ninguna licencia para crear instantáneas o volúmenes replicados. Esta licencia es para la cuenta y se puede utilizar en múltiples sistemas.

Necesitará el número de serie de NetApp que le permite utilizar el servicio durante la duración y la capacidad de la licencia. link:br-start-licensing.html["Aprenda a administrar sus licencias BYOL"].


TIP: La licencia PAYGO no es compatible al hacer copias de seguridad de archivos en almacenamiento compatible con S3.



[[prepare-your-ontap-clusters]]
== Prepare sus clústeres de ONTAP

Prepare su sistema local de origen ONTAP y cualquier sistema local secundario ONTAP o Cloud Volumes ONTAP .

La preparación de sus clústeres ONTAP implica los siguientes pasos:

* Descubra sus sistemas ONTAP en NetApp Console
* Verificar los requisitos del sistema ONTAP
* Verificar los requisitos de red de ONTAP para realizar copias de seguridad de datos en el almacenamiento de objetos
* Verificar los requisitos de red de ONTAP para replicar volúmenes




[[discover-your-ontap-systems-in-netapp-console]]
=== Descubra sus sistemas ONTAP en NetApp Console

Tanto su sistema ONTAP local de origen como cualquier sistema ONTAP local secundario o sistemas Cloud Volumes ONTAP deben estar disponibles en la página *Sistemas* de la NetApp Console .

Necesitará saber la dirección IP de administración del clúster y la contraseña de la cuenta de usuario administrador para agregar el clúster. https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Aprenda a descubrir un clúster"^].



[[verify-ontap-system-requirements]]
=== Verificar los requisitos del sistema ONTAP

Asegúrese de que su sistema ONTAP cumpla con los siguientes requisitos:

* Mínimo de ONTAP 9.8; se recomienda ONTAP 9.8P13 y posterior.
* Una licencia de SnapMirror (incluida como parte del paquete Premium o del paquete de protección de datos).
+
*Nota:* El "Paquete de nube híbrida" no es necesario cuando se utiliza NetApp Backup and Recovery.

+
Aprenda cómo https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["Administrar sus licencias de clúster"^] .

* La hora y la zona horaria están configuradas correctamente.  Aprenda cómo https://docs.netapp.com/us-en/ontap/system-admin/manage-cluster-time-concept.html["Configurar el tiempo de su clúster"^] .
* Si replica datos, verifique que los sistemas de origen y destino ejecuten versiones de ONTAP compatibles.
+
https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["Ver versiones de ONTAP compatibles con las relaciones de SnapMirror"^].





[[verify-ontap-networking-requirements-for-backing-up-data-to-object-storage]]
=== Verificar los requisitos de red de ONTAP para realizar copias de seguridad de datos en el almacenamiento de objetos

Debe asegurarse de que se cumplan los siguientes requisitos en el sistema que se conecta al almacenamiento de objetos.

[NOTE]
====
* Cuando se utiliza una arquitectura de copia de seguridad en abanico, las configuraciones se deben configurar en el sistema de almacenamiento _principal_.
* Cuando se utiliza una arquitectura de copia de seguridad en cascada, las configuraciones se deben configurar en el sistema de almacenamiento _secundario_.
+
link:prev-ontap-protect-journey.html["Obtenga más información sobre los tipos de arquitectura de respaldo"].



====
Se necesitan los siguientes requisitos de red del clúster ONTAP :

* El clúster ONTAP inicia una conexión HTTPS a través de un puerto especificado por el usuario desde el LIF entre clústeres hasta el servidor compatible con S3 para las operaciones de backup y restauración. El puerto se puede configurar durante la configuración del backup.
+
ONTAP lee y escribe datos hacia y desde el almacenamiento de objetos. El almacenamiento de objetos nunca se inicia, simplemente responde.

* ONTAP requiere una conexión entrante desde el agente de la consola al LIF de administración del clúster.
* Se requiere un LIF entre clústeres en cada nodo de ONTAP que aloje los volúmenes que desea respaldar.  El LIF debe estar asociado con el _IPspace_ que ONTAP debe usar para conectarse al almacenamiento de objetos. https://docs.netapp.com/us-en/ontap/networking/standard_properties_of_ipspaces.html["Obtenga más información sobre IPspaces"^] .
+
Cuando configura NetApp Backup and Recovery, se le solicita el espacio IP que desea utilizar. Debes elegir el espacio IP con el que está asociado cada LIF. Ese podría ser el espacio IP "predeterminado" o un espacio IP personalizado que usted creó.

* Los LIF entre clústeres de los nodos pueden acceder al almacén de objetos (no es necesario cuando el agente de consola está instalado en un sitio "oscuro").
* Se han configurado servidores DNS para la máquina virtual de almacenamiento donde se encuentran los volúmenes.  Vea cómo https://docs.netapp.com/us-en/ontap/networking/configure_dns_services_auto.html["Configurar servicios DNS para la SVM"^] .
* Si estás usando un IPspace diferente al Default, entonces puede que necesites crear una ruta estática para acceder al almacén de objetos.
* Actualice las reglas de firewall, si es necesario, para permitir las conexiones del servicio NetApp Backup and Recovery desde ONTAP al almacenamiento de objetos a través del puerto que especificó (normalmente el puerto 443) y el tráfico de resolución de nombres desde la máquina virtual de almacenamiento al servidor DNS a través del puerto 53 (TCP/UDP).




[[verify-ontap-networking-requirements-for-replicating-volumes]]
=== Verificar los requisitos de red de ONTAP para replicar volúmenes

Si planea crear volúmenes replicados en un sistema ONTAP secundario mediante NetApp Backup and Recovery, asegúrese de que los sistemas de origen y destino cumplan con los siguientes requisitos de red.

* Si el clúster está local, debe tener una conexión desde su red corporativa a su red virtual en el proveedor de la nube. Normalmente se trata de una conexión VPN.
* Los clústeres ONTAP deben cumplir requisitos adicionales de subred, puerto, firewall y clúster.




[[activate-backups-on-your-ontap-volumes]]
== Activar copias de seguridad en sus volúmenes ONTAP

Active las copias de seguridad en cualquier momento directamente desde su sistema local.

Un asistente lo guiará a través de los siguientes pasos principales:

* Seleccione los volúmenes que desea respaldar
* Definir la estrategia y las políticas de backup
* Revise sus selecciones


También puedes<<Mostrar los comandos API>> en el paso de revisión, para que pueda copiar el código para automatizar la activación de la copia de seguridad para sistemas futuros.



[[start-the-wizard]]
=== Iniciar el asistente

.Pasos
. Acceda al asistente para activar copias de seguridad y recuperación mediante una de las siguientes maneras:
+
** Desde la página *Sistemas* de la Consola, seleccione el sistema y seleccione *Habilitar > Volúmenes de respaldo* junto a Copia de seguridad y recuperación en el panel derecho.
** Seleccione *Volúmenes* en la barra de Copia de seguridad y recuperación.  Desde la pestaña Volúmenes, seleccione la opción *Acciones (...)* y seleccione *Activar copia de seguridad* para un solo volumen (que aún no tenga habilitada la replicación o la copia de seguridad en el almacenamiento de objetos).


+
La página de Introducción del asistente muestra las opciones de protección, incluidas instantáneas locales, replicaciones y copias de seguridad.  Si realizó la segunda opción en este paso, aparecerá la página Definir estrategia de respaldo con un volumen seleccionado.

. Continúe con las siguientes opciones:
+
** Si ya tienes un agente de consola, ya estás listo.  Simplemente seleccione *Siguiente*.
** Si no tiene un agente de consola, aparece la opción *Agregar un agente de consola*.  Referirse a<<Prepare su agente de consola>> .






[[select-the-volumes-that-you-want-to-back-up]]
=== Seleccione los volúmenes que desea respaldar

Seleccione los volúmenes que desea proteger.  Un volumen protegido es aquel que tiene una o más de las siguientes opciones: política de instantáneas, política de replicación y política de copia de seguridad a objeto.

Puede elegir proteger los volúmenes FlexVol o FlexGroup ; sin embargo, no puede seleccionar una combinación de estos volúmenes al activar la copia de seguridad de un sistema.  Vea cómolink:prev-ontap-backup-manage.html["Activar la copia de seguridad para volúmenes adicionales en el sistema"] (FlexVol o FlexGroup) después de haber configurado la copia de seguridad para los volúmenes iniciales.

[NOTE]
====
* Puede activar una copia de seguridad solo en un único volumen FlexGroup a la vez.
* Al seleccionar los volúmenes de origen que quieres proteger, solo puedes seleccionar aquellos que tengan una configuración de SnapLock coincidente. Los volúmenes que selecciones deben tener todos la función SnapLock activada o todos la función SnapLock desactivada.


====
.Pasos
Tenga en cuenta que si los volúmenes que elija ya tienen políticas de instantáneas o de replicación aplicadas, las políticas que seleccione más adelante sobrescribirán estas políticas existentes.

. En la página Seleccionar volúmenes, seleccione el volumen o los volúmenes que desea proteger.
+
** Opcionalmente, filtre las filas para mostrar solo volúmenes con determinados tipos de volumen, estilos y más para facilitar la selección.
** Después de seleccionar el primer volumen, puede seleccionar todos los volúmenes FlexVol (los volúmenes FlexGroup se pueden seleccionar uno a la vez solamente).  Para realizar una copia de seguridad de todos los volúmenes FlexVol existentes, marque primero un volumen y luego marque la casilla en la fila del título.
** Para realizar una copia de seguridad de volúmenes individuales, marque la casilla de cada volumen.


. Seleccione *Siguiente*.




[[define-the-backup-strategy]]
=== Definir la estrategia de backup

Definir la estrategia de backup implica configurar las siguientes opciones:

* Opciones de protección: si desea implementar una o todas las opciones de respaldo: instantáneas locales, replicación y respaldo en almacenamiento de objetos
* Arquitectura: si desea utilizar una arquitectura de respaldo en cascada o en abanico
* Política de instantáneas locales
* Objetivo y política de replicación
* Realizar copias de seguridad de la información de almacenamiento de objetos (proveedor, cifrado, redes, política de copia de seguridad y opciones de exportación).


.Pasos
. En la página Definir estrategia de respaldo, elija una o todas las siguientes opciones.  Los tres están seleccionados por defecto:
+
** *Instantáneas locales*: Crea instantáneas locales.
** *Replicación*: crea volúmenes replicados en otro sistema de almacenamiento ONTAP .
** *Copia de seguridad*: realiza una copia de seguridad de los volúmenes en un depósito en un sistema ONTAP configurado para S3.


. *Arquitectura*: Si eligió tanto la replicación como la copia de seguridad, elija uno de los siguientes flujos de información:
+
** *En cascada*: los datos de respaldo fluyen del sistema principal al secundario y luego del secundario al almacenamiento de objetos.
** *Distribución en abanico*: los datos de respaldo fluyen desde el sistema principal al secundario _y_ desde el principal al almacenamiento de objetos.
+
Para obtener detalles sobre estas arquitecturas, consultelink:prev-ontap-protect-journey.html["Planifique su viaje de protección"] .



. *Instantánea local*: elija una política de instantáneas existente o cree una nueva.
+

TIP: Si desea crear una política personalizada antes de activar la instantánea, puede usar el Administrador del sistema o la CLI de ONTAP `snapmirror policy create` dominio.  Referirse a .

+

TIP: Para crear una política personalizada mediante Copia de seguridad y recuperación, consultelink:br-use-policies-create.html["Crear una política"] .

+
Para crear una política, seleccione *Crear nueva política* y haga lo siguiente:

+
** Introduzca el nombre de la póliza.
** Seleccione hasta cinco horarios, normalmente de diferentes frecuencias.
** Seleccione *Crear*.


. *Replicación*: Si seleccionó *Replicación*, configure las siguientes opciones:
+
** *Destino de la replicación*: Selecciona el sistema de destino y la Storage VM. Si lo deseas, selecciona el agregado de destino (o los agregados para los volúmenes FlexGroup) y un prefijo o sufijo que se añadirá al nombre del volumen replicado.
** *Política de replicación*: elija una política de replicación existente o cree una nueva.
+
Para crear una política, seleccione *Crear nueva política* y haga lo siguiente:

+
*** Introduzca el nombre de la póliza.
*** Seleccione hasta cinco horarios, normalmente de diferentes frecuencias.
*** Seleccione *Crear*.




. *Copia de seguridad del objeto*: si seleccionó *Copia de seguridad*, configure las siguientes opciones:
+
** *Proveedor*: Seleccione * ONTAP S3*.
** *Configuración del proveedor*: ingrese los detalles del FQDN del servidor S3, el puerto y la clave de acceso y la clave secreta de los usuarios.
+
La clave de acceso y la clave secreta son para el usuario que usted creó para otorgarle al clúster ONTAP acceso al bucket S3.

** *Redes*: elija el espacio IP en el clúster ONTAP de origen donde residen los volúmenes que desea respaldar.  Los LIF entre clústeres para este espacio IP deben tener acceso a Internet saliente (no es necesario cuando el agente de consola está instalado en un sitio "oscuro").
+

TIP: Seleccionar el espacio IP correcto garantiza que NetApp Backup and Recovery pueda configurar una conexión desde ONTAP a su almacenamiento de objetos ONTAP S3.

** *Política de respaldo*: seleccione una política de respaldo existente o cree una nueva.
+

TIP: Puede crear una política con el Administrador del sistema o la CLI de ONTAP .  Para crear una política personalizada mediante la CLI de ONTAP `snapmirror policy create` comando, referirse a .

+

TIP: Para crear una política personalizada mediante Copia de seguridad y recuperación, consultelink:br-use-policies-create.html["Crear una política"] .

+
Para crear una política, seleccione *Crear nueva política* y haga lo siguiente:

+
*** Introduzca el nombre de la póliza.
*** Seleccione hasta cinco horarios, normalmente de diferentes frecuencias.
*** Para las políticas de backup a objetos, configura los ajustes de Datalock y protección contra ransomware. Para más detalles sobre Datalock y la protección contra ransomware, consulta link:prev-ontap-policy-object-options.html["Configuración de la política de copia de seguridad en objeto"].
*** Seleccione *Crear*.


** *Exportar instantáneas existentes al almacenamiento de objetos como archivos de copia de seguridad*: Si existen instantáneas locales para volúmenes en este sistema que coincidan con la etiqueta de programación de copias de seguridad que acaba de seleccionar (por ejemplo, diaria, semanal, etc.), se mostrará este mensaje adicional. Marque esta casilla para que todas las instantáneas históricas se copien en el almacenamiento de objetos como archivos de respaldo para garantizar la protección más completa para sus volúmenes.


. Seleccione *Siguiente*.




[[review-your-selections]]
=== Revise sus selecciones

Esta es la oportunidad de revisar sus selecciones y realizar ajustes, si es necesario.

.Pasos
. En la página Revisar, revise sus selecciones.
. Opcionalmente, marque la casilla para *Sincronizar automáticamente las etiquetas de la política de instantáneas con las etiquetas de la política de replicación y copia de seguridad*.  Esto crea instantáneas con una etiqueta que coincide con las etiquetas de las políticas de replicación y copia de seguridad.  Si las políticas no coinciden, no se crearán copias de seguridad.
. Seleccione *Activar copia de seguridad*.


.Resultado
NetApp Backup and Recovery comienza a realizar las copias de seguridad iniciales de sus volúmenes. La transferencia de línea base del volumen replicado y el archivo de respaldo incluye una copia completa de los datos de origen. Las transferencias posteriores contienen copias diferenciales de los datos de almacenamiento primario contenidos en las instantáneas.

Se crea un volumen replicado en el clúster de destino que se sincronizará con el volumen de almacenamiento principal.

Se crea un bucket S3 en la cuenta de servicio indicada por la clave de acceso S3 y la clave secreta ingresada, y los archivos de respaldo se almacenan allí.

Se muestra el panel de control de copias de seguridad de volumen para que pueda supervisar el estado de las copias de seguridad.

También puede supervisar el estado de los trabajos de copia de seguridad y restauración mediante ellink:br-use-monitor-tasks.html["Página de seguimiento de trabajos"] .



[[show-the-api-commands]]
=== Mostrar los comandos API

Es posible que desee mostrar y, opcionalmente, copiar los comandos API utilizados en el asistente Activar copia de seguridad y recuperación.  Es posible que desee hacer esto para automatizar la activación de la copia de seguridad en sistemas futuros.

.Pasos
. Desde el asistente Activar copia de seguridad y recuperación, seleccione *Ver solicitud de API*.
. Para copiar los comandos al portapapeles, seleccione el icono *Copiar*.

