---
sidebar: sidebar 
permalink: prev-vmware-policy-create.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja sus cargas de trabajo de VMware con NetApp NetApp and Recovery. 
---
= Cree una política para realizar copias de seguridad de almacenes de datos en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede crear una política o utilizar una de las siguientes políticas predefinidas que están disponibles en NetApp Backup and Recovery.

[]
====
*NOTA* Para cambiar hacia y desde las cargas de trabajo de NetApp Backup and Recovery, consultelink:br-start-switch-ui.html["Cambiar a diferentes cargas de trabajo de NetApp Backup and Recovery"] .

====
.Antes de empezar
* Debe crear políticas si no desea editar las políticas predefinidas.
* Para mover copias de seguridad del almacén de objetos al almacenamiento de archivo, debe ejecutar ONTAP 9.10.1 o posterior y Amazon Web Services o Microsoft Azure debe ser el proveedor de la nube.
* Debe configurar el nivel de acceso al archivo para cada proveedor de nube.


.Acerca de esta tarea
Las siguientes políticas predefinidas están disponibles en la consola de NetApp :

|===
| Nombre de la póliza | Etiqueta | Valor de retención 


 a| 
Retención a largo plazo (LTR) diaria de 1 año
 a| 
Diario
 a| 
366



 a| 
5 años de LTR diario
 a| 
Diario
 a| 
1830



 a| 
LTR semanal de 7 años
 a| 
Semanalmente
 a| 
370



 a| 
LTR mensual de 10 años
 a| 
Mensual
 a| 
120

|===
.Pasos
. En la página Máquinas virtuales, en la lista desplegable Configuración, seleccione *Políticas*.
. Seleccione *Crear política*.
. En la sección Detalles de la política, especifique el nombre de la política.
. En la sección Retención, seleccione uno de los tipos de retención y especifique la cantidad de copias de seguridad que desea conservar.
. Seleccione Primario o Secundario como fuente de almacenamiento de respaldo.
. (Opcional) Si desea mover copias de seguridad del almacén de objetos al almacenamiento de archivo después de una cierta cantidad de días para optimizar los costos, seleccione la casilla de verificación *Copias de seguridad de nivel a archivo* e ingrese la cantidad de días después de los cuales se debe archivar la copia de seguridad.
. Seleccione *Crear*.
+

NOTE: No se puede editar ni eliminar una política que esté asociada a un almacén de datos.


