---
sidebar: sidebar 
permalink: task-setup-ca-certificates.html 
keywords: cloud backup, backup and recovery, backup, restore, certificates, protection, security, storagegrid, backup, back up 
summary: Cree un certificado de seguridad para habilitar la comunicación entre NetApp Backup and Recovery y StorageGRID u ONTAP. 
---
= Configura certificados de CA para NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configura los certificados CA para que NetApp Backup and Recovery pueda validar las conexiones seguras con StorageGRID u ONTAP. Sigue los pasos que se apliquen a tu entorno y a los sistemas que quieras proteger.



[[create-a-ca-certificate-for-storagegrid]]
== Crear un certificado de CA para StorageGRID

Si la comunicación entre los contenedores de NetApp Backup and Recovery y StorageGRID debe verificar el certificado de StorageGRID, completa los siguientes pasos.

El certificado generado debe usar el mismo nombre común (CN) y el mismo nombre alternativo del sujeto que proporcionaste en NetApp Backup and Recovery cuando activaste el backup.

.Pasos
. Siga los pasos de la documentación de StorageGRID para crear el certificado de StorageGRID .
+
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-load-balancer-endpoints.html#attach-certificate["Información de StorageGRID sobre la configuración de certificados"]

. Actualice StorageGRID con el certificado si aún no lo ha hecho.
. Inicia sesión en el agente de la consola como usuario raíz. Ejecuta:
+
[source, shell]
----
sudo su
----
. Busca el volumen Docker de NetApp Backup and Recovery (Cloud Backup Service). Ejecuta:
+
[source, shell]
----
docker volume ls | grep cbs
----
+
Ejemplo de salida:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume"
----
+

NOTE: El nombre del volumen difiere entre los modos de implementación Estándar, Privado y Restringido. Este ejemplo utiliza el modo estándar. Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

. Encuentre el punto de montaje del volumen de NetApp Backup and Recovery . Correr:
+
[source, shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Ejemplo de salida:

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data"
----
+

NOTE: El punto de montaje difiere entre los modos de implementación Estándar, Privado y Restringido. Este ejemplo muestra una implementación de nube estándar. Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

. Cambia al directorio del punto de montaje. Ejecuta:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Si el certificado de StorageGRID está firmado por la CA raíz y una CA intermedia, añade ambos  `pem` archivos en un solo archivo llamado  `sgws.crt` en la ubicación actual. No añadas el certificado de hoja a este archivo.




[[steps-for-the-cloudmanagercbs-container]]
=== Pasos para el contenedor cloudmanager_cbs

Habilita la verificación del certificado del servidor StorageGRID en NetApp Backup and Recovery (Cloud Backup Service).

. Cambia al volumen de Docker que encontraste en los pasos anteriores.
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Cambia al directorio de configuración.
+
[source, shell]
----
cd cbs_config
----
. Crea y guarda un archivo de configuración tal y como se muestra a continuación con uno de los siguientes nombres, en función de tu entorno de implementación:
+
** `production-customer.json` para implementaciones en modo estándar y modo restringido
** `darksite-customer.json` para implementaciones en modo privado
+
Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

+
*Archivo de configuración*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Salir del contenedor. Correr:
+
[source, shell]
----
exit
----
. Reanudar `cloudmanager_cbs` . Correr:
+
[source, shell]
----
docker restart cloudmanager_cbs
----




[[steps-for-the-cloudmanagercbscatalog-container]]
=== Pasos para el contenedor cloudmanager_cbs_catalog

A continuación, habilita la verificación del certificado del servidor StorageGRID para el servicio de catalogación.

. Cambia al volumen de Docker:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Configurar el catálogo. Correr:
+
[source, shell]
----
cd cbs_catalog_config
----
. Crea un archivo de configuración tal y como se muestra a continuación con uno de los siguientes nombres, en función de tu entorno de implementación:
+
** `production-customer.json` para implementaciones en modo estándar y modo restringido
** `darksite-customer.json` para implementaciones en modo privado
+
Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

+
*Archivo de configuración del catálogo*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Reiniciar el catálogo. Correr:
+
[source, shell]
----
docker restart cloudmanager_cbs_catalog
----




[[update-the-console-agent-certificate-with-the-storagegrid-certificate-based-on-the-agent-operating-system]]
=== Actualice el certificado del agente de la consola con el certificado StorageGRID según el sistema operativo del agente



==== Ubuntu

. Copia el certificado SGWS en `/usr/local/share/ca-certificates`. Aquí tienes un ejemplo:
+
[source, shell]
----
cp /config/sgws.crt /usr/local/share/ca-certificates/
----
+
dónde `sgws.crt` es el certificado CA raíz.

. Actualiza los certificados del host con el certificado de StorageGRID. Ejecuta:
+
[source, shell]
----
sudo update-ca-certificates
----




==== Red Hat Enterprise Linux

. Copiar el certificado SGWS a `/etc/pki/ca-trust/source/anchors/` .
+
[source, shell]
----
cp /config/sgws.crt /etc/pki/ca-trust/source/anchors/
----
+
dónde `sgws.crt` es el certificado CA raíz.

. Actualice los certificados del host con el certificado StorageGRID .
+
[source, shell]
----
update-ca-trust extract
----
. Actualizar el `ca-bundle.crt`
+
[source, shell]
----
cd /etc/pki/tls/certs/
openssl x509 -in ca-bundle.crt -text -noout
----
. Para comprobar si los certificados están presentes, ejecute el siguiente comando:
+
[source, shell]
----
openssl crl2pkcs7 -nocrl -certfile /etc/pki/tls/certs/ca-bundle.crt | openssl pkcs7 -print_certs | grep subject | head
----




[[create-a-ca-certificate-for-ontap]]
== Crear un certificado de CA para ONTAP

Si la comunicación entre los contenedores de NetApp Backup and Recovery y ONTAP debe validar el certificado de ONTAP, completa los siguientes pasos.

NetApp Backup and Recovery utiliza la dirección IP de gestión del clúster para conectarse a ONTAP. Introduce la dirección IP del clúster en los campos Subject Alternative Name del certificado. Especifica este valor cuando generes la CSR en System Manager.

Utilice la documentación del Administrador del sistema para crear un nuevo certificado CA para ONTAP.

* https://docs.netapp.com/us-en/ontap/authentication/manage-certificates-sm-task.html["Administrar certificados con el Administrador del sistema"]
* https://kb.netapp.com/on-prem/ontap/DM/System_Manager/SM-KBs/How_to_manage_ONTAP_SSL_certificates_via_System_Manager["Cómo administrar certificados SSL de ONTAP con System Manager"]


.Pasos
. Inicia sesión en el agente de la consola como root. Ejecuta:
+
[source, shell]
----
sudo su
----
. Busca el volumen de Docker NetApp Backup and Recovery. Ejecuta:
+
[source, shell]
----
docker volume ls | grep cbs
----
+
Ejemplo de salida:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
+

NOTE: El nombre del volumen difiere entre los modos de implementación Estándar, Privado y Restringido. Este ejemplo muestra una implementación de nube estándar. Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

. Busca el punto de montaje del volumen. Ejecuta:
+
[source, shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Ejemplo de salida:

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
+

NOTE: El punto de montaje difiere entre los modos de implementación Estándar, Privado y Restringido. Este ejemplo muestra una implementación de nube estándar. Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

. Cambia al directorio del punto de montaje. Ejecuta:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Complete uno de los siguientes pasos:
+
** Si el certificado ONTAP está firmado por la CA raíz y una CA intermedia, entonces agregue el `pem` archivos de ambos en un solo archivo llamado `ontap.crt` en la ubicación actual.
** Si el certificado ONTAP está firmado por una sola CA, cambie el nombre del certificado. `pem` archivar como `ontap.crt` y copiarlo en la ubicación actual. No agregue el certificado de hoja a este archivo.






[[steps-for-the-cloudmanagercbs-container]]
=== Pasos para el contenedor cloudmanager_cbs

A continuación, habilita la verificación del certificado del servidor ONTAP en NetApp Backup and Recovery (Cloud Backup Service).

. Cambia al volumen de Docker que encontraste en los pasos anteriores.
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Cambie al directorio de configuración. Correr:
+
[source, shell]
----
cd cbs_config
----
. Crea un archivo de configuración tal y como se muestra a continuación con uno de los siguientes nombres, en función de tu entorno de implementación:
+
** `production-customer.json` para implementaciones en modo estándar y modo restringido
** `darksite-customer.json` para implementaciones en modo privado
+
Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

+
*Archivo de configuración*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Salir del contenedor. Correr:
+
[source, shell]
----
exit
----
. Reinicie NetApp Backup and Recovery. Correr:
+
[source, shell]
----
docker restart cloudmanager_cbs
----




[[steps-for-the-cloudmanagercbscatalog-container]]
=== Pasos para el contenedor cloudmanager_cbs_catalog

Habilita la verificación de certificados del servidor ONTAP para el servicio de catalogación.

. Cambia al volumen de Docker. Ejecuta:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Correr:
+
[source, shell]
----
cd cbs_catalog_config
----
. Crea un archivo de configuración tal y como se muestra a continuación con uno de los siguientes nombres, en función de tu entorno de implementación:
+
** `production-customer.json` para implementaciones en modo estándar y modo restringido
** `darksite-customer.json` para implementaciones en modo privado
+
Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

+
*Archivo de configuración*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Reinicie NetApp Backup and Recovery. Correr:
+
[source, shell]
----
docker restart cloudmanager_cbs_catalog
----




[[create-a-certificate-for-both-ontap-and-storagegrid]]
== Cree un certificado para ONTAP y StorageGRID

Si necesita habilitar el certificado tanto para ONTAP como para StorageGRID, el archivo de configuración se verá así:

*Archivo de configuración para ONTAP y StorageGRID*

[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  },
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----