---
sidebar: sidebar 
permalink: task-setup-ca-certificates.html 
keywords: cloud backup, backup and recovery, backup, restore, certificates, protection, security, storagegrid, backup, back up 
summary: Cree un certificado de seguridad para habilitar la comunicación entre NetApp Backup and Recovery y StorageGRID u ONTAP. 
---
= Configurar certificados de seguridad para StorageGRID y ONTAP en NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cree un certificado de seguridad para habilitar la comunicación entre NetApp Backup and Recovery y StorageGRID u ONTAP.



== Crear un certificado de seguridad para StorageGRID

Si la comunicación entre los contenedores de NetApp Backup and Recovery y StorageGRID debe verificar el certificado de StorageGRID , complete los siguientes pasos.

El certificado generado debe tener CN y nombre alternativo del sujeto como el nombre proporcionado en NetApp Backup and Recovery cuando activó la copia de seguridad.

.Pasos
. Siga los pasos de la documentación de StorageGRID para crear el certificado de StorageGRID .
+
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-load-balancer-endpoints.html#attach-certificate["Información de StorageGRID sobre la configuración de certificados"]

. Actualice StorageGRID con el certificado si aún no lo ha hecho.
. Inicie sesión en el agente de la consola como usuario raíz. Correr:
+
[source, console]
----
sudo su
----
. Obtenga el volumen Docker de NetApp Backup and Recovery (Cloud Backup Service). Correr:
+
[source, console]
----
docker volume ls | grep cbs
----
+
Ejemplo de salida:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume"
----
+

NOTE: El nombre del volumen difiere entre los modos de implementación Estándar, Privado y Restringido. Este ejemplo utiliza el modo estándar. Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

. Encuentre el punto de montaje del volumen de NetApp Backup and Recovery . Correr:
+
[source, console]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Ejemplo de salida:

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data"
----
+

NOTE: El punto de montaje difiere entre los modos de implementación Estándar, Privado y Restringido. Este ejemplo muestra una implementación de nube estándar. Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

. Cambie al directorio MountPoint. Correr:
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Si el certificado de StorageGRID está firmado por la CA raíz y una CA intermedia, entonces agregue el `pem` archivos de ambos en un solo archivo llamado `sgws.crt` en la ubicación actual. No agregue el certificado de hoja a este archivo.




=== Pasos para el contenedor cloudmanager_cbs

Necesitará habilitar la verificación del certificado del servidor StorageGRID en NetApp Backup and Recovery (Cloud Backup Service).

. Cambie los directorios al volumen Docker obtenido en los pasos anteriores.
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Cambie los directorios al directorio de configuración.
+
[source, console]
----
cd cbs_config
----
. Cree y guarde un archivo de configuración como se muestra a continuación con uno de los siguientes nombres según su entorno de implementación:
+
** `production-customer.json`Se utiliza para implementaciones en modo estándar y modo restringido.
** `darksite-customer.json`Se utiliza para implementaciones en modo privado.
+
Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

+
*Archivo de configuración*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Salir del contenedor. Correr:
+
[source, console]
----
exit
----
. Reanudar `cloudmanager_cbs` . Correr:
+
[source, console]
----
docker restart cloudmanager_cbs
----




=== Pasos para el contenedor cloudmanager_cbs_catalog

A continuación, deberá habilitar la verificación del certificado del servidor StorageGRID para el servicio de catalogación.

. Cambiar directorios al volumen Docker:
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Configurar el catálogo. Correr:
+
[source, console]
----
cd cbs_catalog_config
----
. Cree un archivo de configuración como se muestra a continuación con uno de los siguientes nombres según su entorno de implementación:
+
** `production-customer.json`Se utiliza para implementaciones en modo estándar y modo restringido.
** `darksite-customer.json`Se utiliza para implementaciones en modo privado.
+
Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

+
*Archivo de configuración del catálogo*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Reiniciar el catálogo. Correr:
+
[source, console]
----
docker restart cloudmanager_cbs_catalog
----




=== Actualice el certificado del agente de la consola con el certificado StorageGRID según el sistema operativo del agente



==== Ubuntu

. Copiar el certificado SGWS a `/usr/local/share/ca-certificates` . He aquí un ejemplo:
+
[source, console]
----
cp /config/sgws.crt /usr/local/share/ca-certificates/
----
+
dónde `sgws.crt` es el certificado CA raíz.

. Actualice los certificados del host con el certificado StorageGRID . Correr
+
[source, console]
----
sudo update-ca-certificates
----




==== Red Hat Enterprise Linux

. Copiar el certificado SGWS a `/etc/pki/ca-trust/source/anchors/` .
+
[source, console]
----
cp /config/sgws.crt /etc/pki/ca-trust/source/anchors/
----
+
dónde `sgws.crt` es el certificado CA raíz.

. Actualice los certificados del host con el certificado StorageGRID .
+
[source, console]
----
update-ca-trust extract
----
. Actualizar el `ca-bundle.crt`
+
[source, console]
----
cd /etc/pki/tls/certs/
openssl x509 -in ca-bundle.crt -text -noout
----
. Para comprobar si los certificados están presentes, ejecute el siguiente comando:
+
[source, console]
----
openssl crl2pkcs7 -nocrl -certfile /etc/pki/tls/certs/ca-bundle.crt | openssl pkcs7 -print_certs | grep subject | head
----




== Crear un certificado de seguridad para ONTAP

Si la comunicación entre los contenedores de NetApp Backup and Recovery y ONTAP debe validar el certificado de ONTAP , complete los siguientes pasos.

NetApp Backup and Recovery utiliza la IP de administración de clúster para conectarse a ONTAP. Introduzca la dirección IP del clúster en los nombres alternativos del sujeto del certificado. Especifique este paso cuando genere la CSR mediante la interfaz de usuario del Administrador del sistema.

Utilice la documentación del Administrador del sistema para crear un nuevo certificado CA para ONTAP.

* https://docs.netapp.com/us-en/ontap/authentication/manage-certificates-sm-task.html["Administrar certificados con el Administrador del sistema"]
* https://kb.netapp.com/on-prem/ontap/DM/System_Manager/SM-KBs/How_to_manage_ONTAP_SSL_certificates_via_System_Manager["Cómo administrar certificados SSL de ONTAP con System Manager"]


.Pasos
. Inicie sesión en el agente de la consola como root. Correr:
+
[source, console]
----
sudo su
----
. Obtenga el volumen Docker de NetApp Backup and Recovery . Correr:
+
[source, console]
----
docker volume ls | grep cbs
----
+
Ejemplo de salida:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
+

NOTE: El nombre del volumen difiere entre los modos de implementación Estándar, Privado y Restringido. Este ejemplo muestra una implementación de nube estándar. Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

. Obtenga el soporte para el volumen. Correr:
+
[source, console]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Ejemplo de salida:

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
+

NOTE: El punto de montaje difiere entre los modos de implementación Estándar, Privado y Restringido. Este ejemplo muestra una implementación de nube estándar. Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

. Cambiar al directorio del punto de montaje. Correr:
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Complete uno de los siguientes pasos:
+
** Si el certificado ONTAP está firmado por la CA raíz y una CA intermedia, entonces agregue el `pem` archivos de ambos en un solo archivo llamado `ontap.crt` en la ubicación actual.
** Si el certificado ONTAP está firmado por una sola CA, cambie el nombre del certificado. `pem` archivar como `ontap.crt` y copiarlo en la ubicación actual. No agregue el certificado de hoja a este archivo.






=== Pasos para el contenedor cloudmanager_cbs

A continuación, habilite la verificación del certificado del servidor ONTAP en NetApp Backup and Recovery (Cloud Backup Service).

. Cambie los directorios al volumen Docker obtenido en los pasos anteriores.
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Cambie al directorio de configuración. Correr:
+
[source, console]
----
cd cbs_config
----
. Cree un archivo de configuración como se muestra a continuación con uno de los siguientes nombres según su entorno de implementación:
+
** `production-customer.json`Se utiliza para implementaciones en modo estándar y modo restringido.
** `darksite-customer.json`Se utiliza para implementaciones en modo privado.
+
Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

+
*Archivo de configuración*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Salir del contenedor. Correr:
+
[source, console]
----
exit
----
. Reinicie NetApp Backup and Recovery. Correr:
+
[source, console]
----
docker restart cloudmanager_cbs
----




=== Pasos para el contenedor cloudmanager_cbs_catalog

Habilite la verificación del certificado del servidor ONTAP para el servicio de catalogación.

. Cambiar directorios al volumen Docker. Correr:
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Correr:
+
[source, console]
----
cd cbs_catalog_config
----
. Cree un archivo de configuración como se muestra a continuación con uno de los siguientes nombres según su entorno de implementación:
+
** `production-customer.json`Se utiliza para implementaciones en modo estándar y modo restringido.
** `darksite-customer.json`Se utiliza para implementaciones en modo privado.
+
Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"] .

+
*Archivo de configuración*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Reinicie NetApp Backup and Recovery. Correr:
+
[source, console]
----
docker restart cloudmanager_cbs_catalog
----




== Cree un certificado para ONTAP y StorageGRID

Si necesita habilitar el certificado tanto para ONTAP como para StorageGRID, el archivo de configuración se verá así:

*Archivo de configuración para ONTAP y StorageGRID*

[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  },
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----