= Compatibilidad con Podman en RHEL 8 o 9 con Explorar y Restaurar
:allow-uri-read: 




=== Compatibilidad con Podman en RHEL 8 o 9 con Explorar y Restaurar

NetApp Backup and Recovery ahora admite restauraciones de archivos y carpetas en Red Hat Enterprise Linux (RHEL) versiones 8 y 9 mediante el motor Podman.  Esto se aplica al método de exploración y restauración de NetApp Backup and Recovery .

La versión 3.9.40 del agente de consola admite ciertas versiones de Red Hat Enterprise Linux versiones 8 y 9 para cualquier instalación manual del software del agente de consola en un host RHEL 8 o 9, independientemente de la ubicación, además de los sistemas operativos mencionados en https://docs.netapp.com/us-en/console-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["requisitos del anfitrión"^] .  Estas versiones más nuevas de RHEL requieren el motor Podman en lugar del motor Docker.  Anteriormente, NetApp Backup and Recovery tenía dos limitaciones al usar el motor Podman.  Se han eliminado estas limitaciones.

https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-restore.html["Obtenga más información sobre cómo restaurar datos de ONTAP desde archivos de respaldo"].



=== La indexación más rápida del catálogo mejora la búsqueda y la restauración

Esta versión incluye un índice de catálogo mejorado que completa la indexación de referencia mucho más rápido.  Una indexación más rápida le permite utilizar la función de búsqueda y restauración más rápidamente.

https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-restore.html["Obtenga más información sobre cómo restaurar datos de ONTAP desde archivos de respaldo"].
