= Cargas de trabajo KVM compatibles con General Availability (GA)
:allow-uri-read: 




=== Cargas de trabajo KVM compatibles con General Availability (GA)

La compatibilidad con cargas de trabajo KVM ya está disponible de forma general (GA) en NetApp Backup and Recovery.

Para obtener detalles sobre cómo proteger las cargas de trabajo de KVM, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Descripción general de las cargas de trabajo de Protect KVM"] .



=== Cargas de trabajo de Kubernetes compatibles en General Availability (GA)

La compatibilidad con cargas de trabajo de Kubernetes ya está disponible de forma general (GA) en NetApp Backup and Recovery. Esta versión de cargas de trabajo de Kubernetes también introduce las siguientes capacidades mejoradas:

*Soporte para informes*: Ahora puedes generar informes de actividad de protección para clústeres de Kubernetes y aplicaciones protegidas por NetApp Backup and Recovery.

Para obtener detalles sobre cómo proteger las cargas de trabajo de Kubernetes, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Descripción general de las cargas de trabajo de Protect Kubernetes"] .
