= Mejoras en las cargas de trabajo de ONTAP Volumes
:allow-uri-read: 




=== Mejoras en las cargas de trabajo de ONTAP Volumes

En esta versión, las cargas de trabajo de ONTAP Volumes introducen la siguiente mejora:

*Soporte para almacenamiento en la nube compatible con S3*: NetApp Backup and Recovery para cargas de trabajo de Volumes ahora admite la realización de copias de seguridad en almacenamiento en la nube compatible con S3.

Para obtener más información sobre la protección de las cargas de trabajo de ONTAP Volumes, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Descripción general de la protección de cargas de trabajo de ONTAP Volumes"].



=== Mejoras en las cargas de trabajo de Hyper-V

En esta versión, las cargas de trabajo Hyper-V introducen las siguientes mejoras:

* *Mejoras en la restauración de archivos y carpetas en una máquina virtual invitada*: Ahora puedes restaurar archivos y carpetas de una instantánea en el almacenamiento primario o secundario a una máquina virtual de Windows invitada. Esta función ahora es compatible con VMs CIFS y SAN.
* *Los grupos de protección ahora utilizan la programación basada en la zona horaria del host*: Los grupos de protección ahora utilizan la zona horaria del host de Hyper-V. Los grupos de protección creados antes de que se introdujera la programación basada en la zona horaria del host siguen utilizando la hora configurada anteriormente (normalmente UTC). Para actualizar estos grupos de protección y que utilicen la zona horaria del host de Hyper-V, tienes que volver a crear las programaciones. Consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["Crear y administrar grupos de protección para cargas de trabajo de Hyper-V"] para más información.


Para obtener detalles sobre cómo proteger las cargas de trabajo de Hyper-V, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Descripción general de Protect Hyper-V Workloads"] .



=== Mejoras en las cargas de trabajo de VMware

En esta versión, VMware workloads introduce la siguiente mejora:

* *Los grupos de protección ahora utilizan la programación basada en la zona horaria del host*: Los grupos de protección ahora utilizan la zona horaria del servidor VMware vCenter que los aloja. Los grupos de protección creados antes de que se introdujera la programación basada en la zona horaria del host siguen ejecutándose en la zona horaria configurada anteriormente (normalmente UTC). Para usar la zona horaria de vCenter, tienes que volver a crear las programaciones. Consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Crear y administrar grupos de protección para cargas de trabajo de VMware"] para más información.


Para obtener detalles sobre cómo proteger las cargas de trabajo de VMware, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Descripción general de Protect VMware Workloads"] .
