= Anotación de tiempo de espera de data mover
:allow-uri-read: 




== Anotación de tiempo de espera de data mover

Utiliza la anotación `protect.trident.netapp.io/data-mover-timeout-sec` para establecer un tiempo de espera por operación (en segundos) del data mover durante el backup y la restauración. Especifica cuánto tiempo espera un data mover a que una operación avance antes de que se agote el tiempo de espera. Esto es útil para detectar y manejar transferencias atascadas (por ejemplo, cuando los problemas de red impiden el progreso de la restauración de datos de volumen).

Puedes usar esta anotación en tu archivo YAML como se muestra a continuación:

[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: bkp-restore-kopia
  namespace: trident-protect
  annotations: # Optional annotations to configure data movement timeout
    protect.trident.netapp.io/data-mover-timeout-sec: "2"
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
----
En este ejemplo, la anotación falla la  `BackupRestore` operación si no se produce ningún progreso en 2 segundos en la operación de restauración.


NOTE: Si el valor de la anotación es menor o igual a 0, la operación fallará inmediatamente.
