= Anotaciones y etiquetas de namespace durante las operaciones de restauración y conmutación por error
:allow-uri-read: 




== Anotaciones y etiquetas de namespace durante las operaciones de restauración y conmutación por error

Durante la restauración y la conmutación por error, las etiquetas y anotaciones del espacio de nombres de destino se actualizan para que coincidan con las del origen: las claves del origen se añaden a las claves de destino o las sobrescriben, mientras que las claves que solo existen en el destino no se modifican.


NOTE: En Red Hat OpenShift, las anotaciones de espacio de nombres son importantes porque garantizan que los pods restaurados reciban las restricciones y permisos de contexto de seguridad correctos, lo que les permite acceder a los volúmenes y ejecutarse sin errores de permisos. Para más información, consulta link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/managing-pod-security-policies["OpenShift documentación de restricciones de contexto de seguridad"^].

Establece la variable de entorno de Kubernetes

[listing]
----
RESTORE_SKIP_NAMESPACE_ANNOTATIONS
----
antes de la restauración o conmutación por error para evitar que se sobrescriban anotaciones específicas del espacio de nombres de destino. Por ejemplo:

[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set-string restoreSkipNamespaceAnnotations="{<annotation_key_to_skip_1>,<annotation_key_to_skip_2>}" \
  --reuse-values
----

NOTE: Durante la restauración o conmutación por error, las anotaciones y etiquetas de espacios de nombres especificadas en `restoreSkipNamespaceAnnotations` y `restoreSkipNamespaceLabels` se excluyen de la operación de restauración o conmutación por error. Asegúrate de que estos ajustes se configuren durante la instalación inicial de Helm. Para obtener más información, consulta https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Configura los ajustes adicionales del helm chart de Trident Protect"].

Si utilizaste Helm con el indicador `--create-namespace` para instalar la aplicación de origen, Trident Protect copia la etiqueta del nombre al espacio de nombres de destino. Si el valor de la etiqueta coincide con el nombre del espacio de nombres de origen, se reemplaza por el nombre del espacio de nombres de destino; si no, se deja igual.



=== Ejemplo

El siguiente ejemplo muestra los espacios de nombres de origen y destino con diferentes etiquetas y anotaciones, y muestra el espacio de nombres de destino antes y después de la operación para ilustrar cómo se añaden, fusionan o sobrescriben las claves.



==== Antes de la operación de restauración o conmutación por error

La siguiente tabla ilustra el estado de los espacios de nombres de origen y destino de ejemplo antes de la operación de restauración o conmutación por error:

[cols="1,2a,2a"]
|===
| Espacio de nombres | Anotaciones | Etiquetas 


| Namespace ns-1 (fuente)  a| 
* annotation.one/key: "valoractualizado"
* annotation.two/key: "true"

 a| 
* entorno=producción
* compliance=hipaa
* name=ns-1




| Namespace ns-2 (destino)  a| 
* annotation.one/key: "true"
* annotation.three/key: "false"

 a| 
* role=database


|===


==== Después de la operación de restauración

La siguiente tabla ilustra el estado del espacio de nombres de destino de ejemplo después de la operación de restauración o conmutación por error. Se han añadido algunas claves, se han sobrescrito otras y la etiqueta `name` se ha actualizado para que coincida con el espacio de nombres de destino:

[cols="1,2a,2a"]
|===
| Espacio de nombres | Anotaciones | Etiquetas 


| Namespace ns-2 (destino)  a| 
* annotation.one/key: "valoractualizado"
* annotation.two/key: "true"
* annotation.three/key: "false"

 a| 
* name=ns-2
* compliance=hipaa
* entorno=producción
* role=database


|===